-- Migration: Import hotels from MySQL database
-- Source: Phuket_Hotel.csv and Phang_Nga_Hotel.csv
-- Generated: 2025-11-30T11:13:12.835Z
-- Total Phuket Hotels: 1763
-- Total Phang Nga Hotels: 235

-- First, create the reference_hotels table if it doesn't exist
CREATE TABLE IF NOT EXISTS reference_hotels (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name TEXT NOT NULL,
    area TEXT NOT NULL,
    province TEXT NOT NULL DEFAULT 'Phuket',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Clear existing reference_hotels and insert fresh data
TRUNCATE TABLE reference_hotels;

-- =====================================================
-- PHUKET HOTELS (1763 hotels)
-- =====================================================

INSERT INTO reference_hotels (name, area, province) VALUES
('Kamala Phuket Guesthouse', 'Kamala', 'Phuket'),
('Good 9 At Home', 'Rawai', 'Phuket'),
('Naiharn Garden Resort Vil', 'Rawai', 'Phuket'),
('Palm Oasis Boutique Hotel', 'Rawai', 'Phuket'),
('OYO 1037 Kamala Phuket Guesthouse', 'Kamala', 'Phuket'),
('Baan Kamala Hostel and Guesthouse', 'Kamala', 'Phuket'),
('At Kamala', 'Kamala', 'Phuket'),
('Surintra Boutique Resort', 'Surin', 'Phuket'),
('Lespalm Waterfall Pool Villa', 'Surin', 'Phuket'),
('Discovery House Hotel', 'Sakhu', 'Phuket'),
('Airport Phuket Garden Resort', 'Sakhu', 'Phuket'),
('Baantonsai Garden Resort', 'Patong', 'Phuket'),
('Larn Park Resortel', 'Patong', 'Phuket'),
('Karon Studio Service Apartment', 'Karon', 'Phuket'),
('Welcome Guest House', 'Patong', 'Phuket'),
('Welcome Inn Hotel Karon Beach', 'Karon', 'Phuket'),
('De Blue At Sea Rawai Hotel', 'Rawai', 'Phuket'),
('Elcidium Boutique Guesthouse', 'Karon', 'Phuket'),
('Jazz U Garden Resort', 'Karon', 'Phuket'),
('Capannina Inn', 'Kata', 'Phuket'),
('Oceanstone by Holy Cow', 'Choeng Thale', 'Phuket'),
('Allamanda room 3122 Laguna', 'Choeng Thale', 'Phuket'),
('Bk Villa', 'Thep Krasattri', 'Phuket'),
('Layan Beach Resort & Spa Village', 'Layan', 'Phuket'),
('Tyler Naiyang', 'Nai Yang', 'Phuket'),
('Wecare Hostel Naiyang', 'Nai Yang', 'Phuket'),
('OYO 1117 Phuket Airport Suites', 'Nai Yang', 'Phuket'),
('JJW House Phuket', 'Sakhu', 'Phuket'),
('OYO 433 Iwp Wake Park & Resort Hotel', 'Mai Khao', 'Phuket'),
('Maikhao Beach Guest House', 'Mai Khao', 'Phuket'),
('Bungalow@Maikhao', 'Mai Khao', 'Phuket'),
('Maikhao Boutique Hostel', 'Mai Khao', 'Phuket'),
('Summer Breeze Inn', 'Phuket Town', 'Phuket'),
('Yuwadee Resort', 'Chalong', 'Phuket'),
('OYO 368 Aoi Apartment', 'Chalong', 'Phuket'),
('Anda Orange Pier Guesthouse', 'Chalong', 'Phuket'),
('Supergreen Hotel', 'Chalong', 'Phuket'),
('Vimonsiri Hill Resort & Spa', 'Chalong', 'Phuket'),
('Patong Eyes', 'Patong', 'Phuket'),
('Chusri Hotel - SHA Extra Plus', 'Patong', 'Phuket'),
('Stanley''s Guesthouse', 'Phuket', 'Phuket'),
('Guesthouse Belvedere', 'Patong', 'Phuket'),
('The Luka Guesthouse and Restaurant', 'Patong', 'Phuket'),
('Patong 7Days Premium Hotel Phuket', 'Patong', 'Phuket'),
('Baramee Hip Hotel', 'Patong', 'Phuket'),
('SK Residence', 'Phuket', 'Phuket'),
('Relax Guest House', 'Patong', 'Phuket'),
('Desire Guesthouse Patong', 'Patong', 'Phuket'),
('Rayaan 6 Guesthouse', 'Patong', 'Phuket'),
('Rayaan Guest House', 'Patong', 'Phuket'),
('Ansino Bukit', 'Patong', 'Phuket'),
('Phuket Paradise Hotel', 'Patong', 'Phuket'),
('A Casa Di Luca Patong', 'Patong', 'Phuket'),
('New Era Guesthouse', 'Patong', 'Phuket'),
('Small Shells', 'Patong', 'Phuket'),
('OYO 605 Lake View Phuket Place', 'Phuket', 'Phuket'),
('Charin Village', 'Chalong', 'Phuket'),
('Studio 77 Phuket', 'Chalong', 'Phuket'),
('Ocean12 Chic Hotel', 'Chalong', 'Phuket'),
('Gamers Paradise Hotel', 'Chalong', 'Phuket'),
('BaanSattaBun', 'Chalong', 'Phuket'),
('OYO 466 Vibes Patong', 'Patong', 'Phuket'),
('Sea view Panwa Cottage Hostel', 'Cape Panwa', 'Phuket'),
('OYO 617 Tira Hostel @ Chalong Phuket', 'Chalong', 'Phuket'),
('Sunset Seaside Beachfront', 'Cape Panwa', 'Phuket'),
('ZEN Premium Chalong Phuket', 'Chalong', 'Phuket'),
('Patong Panomporn Phuket', 'Patong', 'Phuket'),
('Emerald Terrace Apartment Patong By OHM', 'Patong', 'Phuket'),
('OYO 1032 Beds Patong', 'Patong', 'Phuket'),
('Guesthouse Belvedere - Lovely Room for 2 People, Free Ac and Wi-fi', 'Patong', 'Phuket'),
('Bucintoro Restaurant & Guesthouse Belvedere - Central Double Room With Ac & Wifi', 'Patong', 'Phuket'),
('Green Mango Guesthouse - Hostel', 'Wichit', 'Phuket'),
('Centre Point Nanai', 'Patong', 'Phuket'),
('Loveli Boutique Guesthouse', 'Phuket', 'Phuket'),
('The Coconut Nanai Resort', 'Patong', 'Phuket'),
('Buasri Boutique Patong', 'Patong', 'Phuket'),
('The Landmark Patong', 'Patong', 'Phuket'),
('The Bed Hostel at Patong', 'Patong', 'Phuket'),
('Sabai Inn Patong Phuket', 'Patong', 'Phuket'),
('Patong Blue - Hostel', 'Patong', 'Phuket'),
('Same Same Guesthouse', 'Patong', 'Phuket'),
('7 Sky Residency', 'Patong', 'Phuket'),
('ME Hotel Beach View - Hostel', 'Patong', 'Phuket'),
('Enrico Hostel Patong', 'Patong', 'Phuket'),
('Royal Swiss Guest House', 'Patong', 'Phuket'),
('Sawasdee Mansion', 'Patong', 'Phuket'),
('BL Rabbit hotel', 'Rawai', 'Phuket'),
('Som Guesthouse', 'Phuket', 'Phuket'),
('กะทู้', 'Phuket', 'Phuket'),
('The Lantine Hostel', 'Chalong', 'Phuket'),
('Patong RK', 'Patong', 'Phuket'),
('Smile Inn Patong', 'Patong', 'Phuket'),
('OYO 423 Baan Lucky Guesthouse', 'Karon', 'Phuket'),
('Panda hotel', 'Patong', 'Phuket'),
('Room Actually by Zuzu', 'Karon', 'Phuket'),
('White Snapper Kitchen & Guesthouse', 'Karon', 'Phuket'),
('Welcome Inn Hotel Karon Beach', 'Karon', 'Phuket'),
('The Ark By Veloche Group', 'Karon', 'Phuket'),
('Karon Sunshine Guesthouse & Bar', 'Karon', 'Phuket'),
('Nin Apartments Karon Beach', 'Karon', 'Phuket'),
('Roberto''s Guesthouse', 'Karon', 'Phuket'),
('Karon Cliff Contemporary Boutique Bungalows', 'Karon', 'Phuket'),
('Phuket Racha Guesthouse', 'Phuket Town', 'Phuket'),
('Pitstop Restaurant and Guesthouse', 'Kata', 'Phuket'),
('Sharaya Kata Hotel', 'Kata', 'Phuket'),
('Hotel Surf Blue Kata', 'Kata', 'Phuket'),
('The Bedroom Nai Harn Beach', 'Rawai', 'Phuket'),
('Get Along Residence', 'Si Sunthon', 'Phuket'),
('Thaimond Residence by TropicLook', 'Rawai', 'Phuket'),
('Le''Da Hotel Sha', 'Rawai', 'Phuket'),
('Le'' Da Hotel', 'Rawai', 'Phuket'),
('Room in B&B - Belvedere - Bucintoro', 'Patong', 'Phuket'),
('Butterfly House', 'Patong', 'Phuket'),
('Asia Inn', 'Phuket', 'Phuket'),
('Patong Cottage', 'Patong', 'Phuket'),
('Thai Corner Hotel Patong', 'Patong', 'Phuket'),
('Mild Guesthouse', 'Patong', 'Phuket'),
('Sabai Inn Patong', 'Patong', 'Phuket'),
('G&B Guesthouse', 'Patong', 'Phuket'),
('Adonis Guest House', 'Patong', 'Phuket'),
('Five hundred miles Hostel', 'Patong', 'Phuket'),
('Exhicon New Life Classic', 'Wichit', 'Phuket'),
('Patong Premier Resort', 'Patong', 'Phuket'),
('Ping An Hotel', 'Patong', 'Phuket'),
('Patong Pearl Hotel', 'Patong', 'Phuket'),
('Slumber Party Patong', 'Patong', 'Phuket'),
('Rayaan Oriental Guest House & Restaurant', 'Patong', 'Phuket'),
('OYO 250 July Hotel Patong', 'Patong', 'Phuket'),
('Cool Sea House', 'Patong', 'Phuket'),
('Nina''s Guest House 2', 'Phuket', 'Phuket'),
('2025-01-23 02:46:35', 'Phuket', 'Phuket'),
('OYO 277 Pumpui Boutique Hotel', 'Patong', 'Phuket'),
('Fish and summer House', 'Phuket', 'Phuket'),
('Memory 2', 'Patong', 'Phuket'),
('Thira Residence Patong', 'Patong', 'Phuket'),
('Rawai Suites Phuket', 'Rawai', 'Phuket'),
('Colora Hotel', 'Patong', 'Phuket'),
('Condo in Karon in Chic Condo - Unit B505', 'Karon', 'Phuket'),
('Leelawadee Boutique Hotel', 'Wichit', 'Phuket'),
('Lemongrass Hotel', 'Phuket', 'Phuket'),
('Sharaya Patong Hotel', 'Patong', 'Phuket'),
('Blue Ocean Studio', 'Patong', 'Phuket'),
('Sharaya Boutique Hotel Patong', 'Patong', 'Phuket'),
('OYO 444 Sea Beach Paradise', 'Patong', 'Phuket'),
('Happy Fish Guesthouse', 'Patong', 'Phuket'),
('Grande Elegance Serviced Apartment', 'Patong', 'Phuket'),
('Kata Ocean View Wellness D7', 'Kata', 'Phuket'),
('Welcome Inn Hotel Karon Beach', 'Karon', 'Phuket'),
('Welcome Inn Hotel Karon Beach Double Superior Room From Only 700 Baht', 'Karon', 'Phuket'),
('Dreamz House Boutique', 'Karon', 'Phuket'),
('Thira House', 'Phuket', 'Phuket'),
('Chanpirom Boutique Hotel', 'Karon', 'Phuket'),
('Capri Inn', 'Phuket', 'Phuket'),
('Baan Kawkaew Kata', 'Kata', 'Phuket'),
('Khok Chang Building', 'Karon', 'Phuket'),
('Grand Nai Harn Suites', 'Rawai', 'Phuket'),
('OYO 75344 Ban Elephant Blanc Apartment', 'Kata', 'Phuket'),
('Rama Kata Beach Hotel', 'Kata', 'Phuket'),
('The Pool at Thalassa Kata Beach', 'Kata', 'Phuket'),
('Natalie House Kata Beach', 'Kata', 'Phuket'),
('TP Hostel Kata Beach Phuket', 'Kata', 'Phuket'),
('OYO 1005 Pacotte Boutique Resort', 'Rawai', 'Phuket'),
('Freedom Kata Hotel', 'Kata', 'Phuket'),
('Kata Country House', 'Kata', 'Phuket'),
('OYO 744 @Home Kamala Hills', 'Kamala', 'Phuket'),
('Da Moreno Rawai', 'Rawai', 'Phuket'),
('Family Guesthouse Rawai', 'Rawai', 'Phuket'),
('The Nice Mangoes', 'Rawai', 'Phuket'),
('OYO 450 Rawai Studios Resort', 'Rawai', 'Phuket'),
('Grand Blue Kamala', 'Kamala', 'Phuket'),
('Circle Phuket Resort & Spa', 'Kamala', 'Phuket'),
('Sure Guesthouse', 'Kamala', 'Phuket'),
('Chollada Inn', 'Kamala', 'Phuket'),
('Sirin Bungalow', 'Choeng Thale', 'Phuket'),
('The Aristo Resort 202 by Holy Cow', 'Surin', 'Phuket'),
('Nice Nap Hostel', 'Sakhu', 'Phuket'),
('OYO 1029 Os Rooms', 'Nai Yang', 'Phuket'),
('MEMO Residence - Hostel', 'Mai Khao', 'Phuket'),
('Betterview Bed Breakfast & Bungalow', 'Phuket', 'Phuket'),
('Ruankaew Homestay', 'Mai Khao', 'Phuket'),
('OYO 75373 Chamil House', 'Thalang', 'Phuket'),
('OYO 669 Koh Yao Beach Bungalows', 'Phuket', 'Phuket'),
('Racha HiFi Homestay', 'Phuket Town', 'Phuket'),
('Nasa Mansion', 'Phuket Town', 'Phuket'),
('Ananas Phuket Central Hostel - Adults Only', 'Wichit', 'Phuket'),
('Carpio Hotel Phuket', 'Phuket Town', 'Phuket'),
('Sky Silk Decoration House', 'Patong', 'Phuket'),
('Bangkok Residence', 'Patong', 'Phuket'),
('The Allano Phuket Hotel', 'Patong', 'Phuket'),
('Azure Bangla Phuket', 'Patong', 'Phuket'),
('Paksaa Boutique Hotel Patong Phuket', 'Patong', 'Phuket'),
('Ash Lodge', 'Patong', 'Phuket'),
('Chongko Guesthouse', 'Patong', 'Phuket'),
('Troy Patong by NSW', 'Patong', 'Phuket'),
('Roar Inn Patong', 'Patong', 'Phuket'),
('Wire Hostel Patong', 'Patong', 'Phuket'),
('Hangover Inn', 'Patong', 'Phuket'),
('Patong Terrace', 'Patong', 'Phuket'),
('Sanga Villas', 'Patong', 'Phuket'),
('Kudo Hotel', 'Patong', 'Phuket'),
('Goldsea Beach', 'Patong', 'Phuket'),
('Chic Condo', 'Patong', 'Phuket'),
('Azure Phuket Hotel', 'Patong', 'Phuket'),
('Santi White House Patong Hotel', 'Patong', 'Phuket'),
('Blue Star Hotel', 'Patong', 'Phuket'),
('Saiyuan Estate by TropicLook', 'Rawai', 'Phuket'),
('Silla Patong Hostel', 'Patong', 'Phuket'),
('Knock Knock Beach Boutique', 'Patong', 'Phuket'),
('Haven Lagoon Condominium', 'Patong', 'Phuket'),
('Absolute Sea Pearl Beach Resort', 'Patong', 'Phuket'),
('Le Chada Villa', 'Karon', 'Phuket'),
('Welcome Inn Karon', 'Karon', 'Phuket'),
('The Kris Residence', 'Patong', 'Phuket'),
('OYO 255 The Ocean Hotel Patong', 'Patong', 'Phuket'),
('Avantika Boutique Hotel', 'Patong', 'Phuket'),
('OYO 328 Onion House', 'Karon', 'Phuket'),
('Samakkee Resort', 'Rawai', 'Phuket'),
('BaanNueng at Kata', 'Kata', 'Phuket'),
('South Siam Guesthouse', 'Kata', 'Phuket'),
('Glitter House', 'Kata', 'Phuket'),
('Simply Hotel', 'Kata', 'Phuket'),
('OYO 453 Thai Boutique Resort', 'Rawai', 'Phuket'),
('Cool Breeze Bungalows', 'Kata', 'Phuket'),
('Kata Hiview Resort', 'Kata', 'Phuket'),
('CAPITAL O847 Orchid Garden Villa', 'Rawai', 'Phuket'),
('Kokyang Estate by Tropiclook', 'Rawai', 'Phuket'),
('CAPITAL O887 Orchid Garden Villa 2', 'Rawai', 'Phuket'),
('Spaboat', 'Rawai', 'Phuket'),
('Pool Access 89 at Rawai', 'Rawai', 'Phuket'),
('Room 4 Smart Travelers Rawai', 'Rawai', 'Phuket'),
('Nicha Residence', 'Kamala', 'Phuket'),
('Kamala Cool Hotel', 'Kamala', 'Phuket'),
('The Mamatel Boutique', 'Kamala', 'Phuket'),
('La Maison Ya Nui Resort Phuket', 'Rawai', 'Phuket'),
('OYO 259 Baan Napatr', 'Choeng Thale', 'Phuket'),
('Classic Home', 'Bang Tao', 'Phuket'),
('Nice Lagoon Beach', 'Choeng Thale', 'Phuket'),
('Surin Sweet Hotel', 'Surin', 'Phuket'),
('Lin House', 'Phuket Town', 'Phuket'),
('At Panta Phuket', 'Sakhu', 'Phuket'),
('Kittiya Mansion', 'Phuket Town', 'Phuket'),
('Private Pool Villas by The Slate', 'Nai Yang', 'Phuket'),
('Seapines Villa Liberg', 'Nai Yang', 'Phuket'),
('Happy Mountain Airport Resort', 'Sakhu', 'Phuket'),
('Tanamas House', 'Phuket Town', 'Phuket'),
('Sleepwell@Naiyang', 'Nai Yang', 'Phuket'),
('Naiyang Beach Hotel', 'Nai Yang', 'Phuket'),
('Sabai Sure Hostel', 'Phuket Town', 'Phuket'),
('Hubb Hostel Phuket Airport', 'Sakhu', 'Phuket'),
('Sirikul Mansion', 'Phuket Town', 'Phuket'),
('Laemsai Resort', 'Kamala', 'Phuket'),
('Room Hostel at Phuket Airport', 'Sakhu', 'Phuket'),
('Sunset Resort', 'Patong', 'Phuket'),
('OYO 435 Frame Residence', 'Phuket Town', 'Phuket'),
('Sansuko Ville Bungalow Resort', 'Phuket Town', 'Phuket'),
('OYO 736 Green Poshtel - Hostel', 'Wichit', 'Phuket'),
('OYO 586 I Hostel', 'Phuket Town', 'Phuket'),
('Pause Kathu - Hostel', 'Kathu', 'Phuket'),
('Suuko Wellness and Spa Resort', 'Phuket', 'Phuket'),
('Pon House', 'Chalong', 'Phuket'),
('Chalong Hill Tropical Garden Homes', 'Chalong', 'Phuket'),
('4 Houses Boutique Resort Phuket', 'Chalong', 'Phuket'),
('Airport Hostel Phuket', 'Wichit', 'Phuket'),
('Shanmen Art House', 'Patong', 'Phuket'),
('Kelly’s Residency', 'Patong', 'Phuket'),
('Ol''Masta Hotel & Lounge', 'Patong', 'Phuket'),
('Patong Gallery Hotel', 'Patong', 'Phuket'),
('Tyler Kathu', 'Kathu', 'Phuket'),
('Hilltop Hotel', 'Patong', 'Phuket'),
('OYO 1101 Tanrak Bungalow', 'Kathu', 'Phuket'),
('Escape Villa', 'Phuket Town', 'Phuket'),
('Breezy Andaman', 'Patong', 'Phuket'),
('Baan Boa Guest House', 'Patong', 'Phuket'),
('Andaman Boutique Patong', 'Patong', 'Phuket'),
('Fulla Place', 'Patong', 'Phuket'),
('Sea Star Patong Hotel', 'Patong', 'Phuket'),
('Grand View', 'Patong', 'Phuket'),
('The Bluewater Hotel', 'Patong', 'Phuket'),
('Eriksson Guesthouse', 'Patong', 'Phuket'),
('Palma Resort', 'Patong', 'Phuket'),
('Chang Club', 'Patong', 'Phuket'),
('Centro at Sansabai', 'Patong', 'Phuket'),
('IL MARE PATONG PLACE', 'Patong', 'Phuket'),
('Qhkl Hotel', 'Patong', 'Phuket'),
('Thai Classic Hotel', 'Patong', 'Phuket'),
('Panda Boutique Hotel Phuket', 'Patong', 'Phuket'),
('Tropical Sunset Hotel Patong', 'Patong', 'Phuket'),
('Guan Chao Yin Hotel', 'Patong', 'Phuket'),
('Cat Story Hotel', 'Chalong', 'Phuket'),
('Patong Station House', 'Patong', 'Phuket'),
('Inn Patong Beach Hotel, Phuket', 'Patong', 'Phuket'),
('Ratana Patong Beach Hotel by Shanaya', 'Patong', 'Phuket'),
('Hotel Sea Princess', 'Phuket Town', 'Phuket'),
('Patong Terrace Boutique Hotel', 'Patong', 'Phuket'),
('Elite Guesthouse', 'Patong', 'Phuket'),
('Sea Room''s at Patong', 'Patong', 'Phuket'),
('Lars-Lita Residence', 'Patong', 'Phuket'),
('Lords Palace', 'Patong', 'Phuket'),
('Patong Beach Bed and Breakfast', 'Patong', 'Phuket'),
('Sharaya Residence Patong', 'Patong', 'Phuket'),
('Patong Swiss', 'Patong', 'Phuket'),
('Boondaree Home Resort', 'Karon', 'Phuket'),
('Washington Residence', 'Karon', 'Phuket'),
('Villa Tona Phuket', 'Karon', 'Phuket'),
('Living by Grace', 'Si Sunthon', 'Phuket'),
('SP Residence Phuket', 'Phuket', 'Phuket'),
('Doolay Beachfront Hostel', 'Karon', 'Phuket'),
('Be My Guest Boutique Hotel', 'Karon', 'Phuket'),
('Eazy Resort', 'Kata', 'Phuket'),
('At Zea Hotel Phuket', 'Tri Trang', 'Phuket'),
('Two Villas Holiday Oriental Style Naiharn Beach', 'Rawai', 'Phuket'),
('Purimas Resortel', 'Phuket', 'Phuket'),
('The Trees Club Resort', 'Kamala', 'Phuket'),
('Casa DeeDee (Dee Inn)', 'Rawai', 'Phuket'),
('Golden Teak Resort - Baan Sapparot', 'Kamala', 'Phuket'),
('Sawasdee Rawai Phuket', 'Rawai', 'Phuket'),
('Nai Harn Condominium', 'Rawai', 'Phuket'),
('Villa Oxavia', 'Rawai', 'Phuket'),
('Grand Bleu Ocean View Pool Suite', 'Kamala', 'Phuket'),
('Rawai Paradise', 'Rawai', 'Phuket'),
('The Club Kamala Beach Phuket', 'Kamala', 'Phuket'),
('Rojjana Residence', 'Kamala', 'Phuket'),
('Serene Boutique Garden Resorts', 'Pa Klok', 'Phuket'),
('Yanui Beach Hideaway', 'Rawai', 'Phuket'),
('Diamond Condominium 2706', 'Choeng Thale', 'Phuket'),
('The Aristo by Holy Cow 420', 'Choeng Thale', 'Phuket'),
('Infinity Pool 1 Bedroom at Surin Beach', 'Surin', 'Phuket'),
('Bangtao Tropical Residence Resort & Spa', 'Bang Tao', 'Phuket'),
('Oceanstone Phuket by Holy Cow 1-BR room', 'Choeng Thale', 'Phuket'),
('Areeca Mahogany Zone', 'Choeng Thale', 'Phuket'),
('The Aristo Beach Resort Surin', 'Surin', 'Phuket'),
('Two Villas Holiday Oriental Style Layan Beach', 'Thalang', 'Phuket'),
('Nada Place Layan', 'Layan', 'Phuket'),
('The White House Koh Yao Yai Resort', 'Phuket', 'Phuket'),
('Bussarin Apartment', 'Phuket', 'Phuket'),
('Pasai Cottage', 'Phuket', 'Phuket'),
('Mookdamun Bungalows', 'Phuket', 'Phuket'),
('Lulu Hotel', 'Phuket Town', 'Phuket'),
('Laila Pool Village', 'Phuket', 'Phuket'),
('Hotel on Hilltop', 'Kathu', 'Phuket'),
('The Cozy', 'Patong', 'Phuket'),
('Phuket Botanic Resort', 'Chalong', 'Phuket'),
('The Bird Cage Patong Guesthouse', 'Patong', 'Phuket'),
('OYO 345 The Click Guesthouse At Chalong', 'Rawai', 'Phuket'),
('Sapaan Pla Residence', 'Rawai', 'Phuket'),
('Game Boutique', 'Patong', 'Phuket'),
('Beehive Magenta Patong Hostel', 'Patong', 'Phuket'),
('Alen Guest House', 'Patong', 'Phuket'),
('Chic Boutique Hotel', 'Patong', 'Phuket'),
('DB Residence', 'Patong', 'Phuket'),
('A&J Boutique Hotel Nanai', 'Patong', 'Phuket'),
('Tuana Blue Sky Patong', 'Patong', 'Phuket'),
('Bedbox Guesthouse & Hostel', 'Patong', 'Phuket'),
('The C Park Phuket', 'Patong', 'Phuket'),
('Mali Garden Resort', 'Phuket', 'Phuket'),
('Putter House', 'Phuket', 'Phuket'),
('Nakara spa phuket', 'Patong', 'Phuket'),
('The Room Patong Hotel', 'Patong', 'Phuket'),
('OYO 422 Jane Homestay And Resort', 'Rawai', 'Phuket'),
('OYO 851 On Hill Residence Patong', 'Patong', 'Phuket'),
('Priew Wan Guesthouse', 'Patong', 'Phuket'),
('The Corner Hotel', 'Kathu', 'Phuket'),
('BE Rendez Vous Hotel', 'Patong', 'Phuket'),
('Chill Patong Hotel', 'Patong', 'Phuket'),
('AT HOME hotel&service', 'Chalong', 'Phuket'),
('OYO 288 The Minotel Hotel', 'Patong', 'Phuket'),
('TJ House Patong', 'Patong', 'Phuket'),
('Lupta Hostel', 'Patong', 'Phuket'),
('Platinum Hotel', 'Patong', 'Phuket'),
('The Shades Boutique Hotel Patong Phuket', 'Patong', 'Phuket'),
('Sea Safari', 'Si Sunthon', 'Phuket'),
('Asena Karon Resort', 'Karon', 'Phuket'),
('Allstar Guesthouse', 'Karon', 'Phuket'),
('Bamboo House Phuket', 'Rawai', 'Phuket'),
('Kata Bella Resort', 'Kata', 'Phuket'),
('Rice Restaurant & Rooms', 'Patong', 'Phuket'),
('JR Siam Kata Resort', 'Kata', 'Phuket'),
('Batic House By Sharaya Hotel', 'Karon', 'Phuket'),
('Merit Hill', 'Karon', 'Phuket'),
('Stay@kata Poshtel - Hostel', 'Kata', 'Phuket'),
('Shanti Estate by Tropiclook', 'Rawai', 'Phuket'),
('Paradise Beach Backpackers Hostel', 'Patong', 'Phuket'),
('Boutique Guesthouse by Clearhouse', 'Phuket', 'Phuket'),
('Near Beach Hostel - Adults Only', 'Choeng Thale', 'Phuket'),
('Journey Residence Phuket', 'Choeng Thale', 'Phuket'),
('Parida Resort', 'Choeng Thale', 'Phuket'),
('The Aristo Resort Phuket by Holy Cow 218', 'Choeng Thale', 'Phuket'),
('Wanaburi Hotel', 'Thep Krasattri', 'Phuket'),
('The Stand By Phuket Airport', 'Nai Yang', 'Phuket'),
('Jinda Resort', 'Sakhu', 'Phuket'),
('PP Residence Phuket', 'Nai Yang', 'Phuket'),
('Pranee Mansion Airport', 'Sakhu', 'Phuket'),
('Airport Mansion Phuket', 'Mai Khao', 'Phuket'),
('Nam Naka Boutique Hotel', 'Phuket Town', 'Phuket'),
('MeeTangNangNon Bed&Breakfast', 'Phuket Town', 'Phuket'),
('De42 Hotel', 'Kathu', 'Phuket'),
('Crystal Wild Resort Panwa Phuket', 'Phuket Town', 'Phuket'),
('The Bel Air Resort & Spa - Panwa, Phuket', 'Wichit', 'Phuket'),
('Baba La Casa Hotel', 'Chalong', 'Phuket'),
('The Pixel Panwa', 'Phuket Town', 'Phuket'),
('Diana Pool Access Phuket', 'Chalong', 'Phuket'),
('Dee Viking Hotel Patong', 'Patong', 'Phuket'),
('Silla Loft', 'Patong', 'Phuket'),
('Meesuk Place', 'Patong', 'Phuket'),
('Cello Hotel', 'Patong', 'Phuket'),
('88 Hotel Phuket', 'Patong', 'Phuket'),
('Hanuman Residence', 'Patong', 'Phuket'),
('OYO 996 Phunara Residence', 'Patong', 'Phuket'),
('@ White Patong', 'Patong', 'Phuket'),
('Andatel Grandé Patong Phuket', 'Patong', 'Phuket'),
('New Patong Premier Resort', 'Patong', 'Phuket'),
('Sweet Home Patong', 'Patong', 'Phuket'),
('Baan Ketkeaw Guesthouse 1', 'Patong', 'Phuket'),
('Minatale Phuket', 'Phuket', 'Phuket'),
('Lavender Hotel', 'Phuket', 'Phuket'),
('Saladee Gallery Residence', 'Patong', 'Phuket'),
('Onibaku Hotel', 'Patong', 'Phuket'),
('Happy Holiday Resort and Apartment', 'Patong', 'Phuket'),
('Fruit Paradise Hotel', 'Patong', 'Phuket'),
('Frog House Bed & Breakfast - Adults Only - Hostel', 'Phuket', 'Phuket'),
('Sunflower HLD Hotel', 'Patong', 'Phuket'),
('Patong Buri Hotel', 'Patong', 'Phuket'),
('Benetti House', 'Patong', 'Phuket'),
('Blue Ocean Resort', 'Patong', 'Phuket'),
('Renoir boutique hotel', 'Patong', 'Phuket'),
('At We Patong hostel', 'Patong', 'Phuket'),
('Kanita Garden At Phuket', 'Karon', 'Phuket'),
('Wynn House', 'Karon', 'Phuket'),
('Nori House Kata Beach', 'Kata', 'Phuket'),
('The Guide Hometel', 'Phuket', 'Phuket'),
('Thailand', 'Phuket', 'Phuket'),
('Malinda Villa Phuket', 'Pa Klok', 'Phuket'),
('The Seaton House Phuket', 'Rawai', 'Phuket'),
('The Boathouse Phuket', 'Kata', 'Phuket'),
('Niche Villas by TropicLook', 'Rawai', 'Phuket'),
('Wabi-Sabi Kamala Falls Boutique Residences Resort', 'Kamala', 'Phuket'),
('JT Guesthouse', 'Kamala', 'Phuket'),
('The Quarter Resort Phuket', 'Choeng Thale', 'Phuket'),
('The Aristo Resort', 'Choeng Thale', 'Phuket'),
('Sweet Bungalow', 'Choeng Thale', 'Phuket'),
('Sang Un Bungalow', 'Phuket', 'Phuket'),
('Modern Resort at Naiyang', 'Nai Yang', 'Phuket'),
('OYO 1075 The View at Naiyang', 'Nai Yang', 'Phuket'),
('OYO 325 Naiyang Cottage', 'Nai Yang', 'Phuket'),
('Slowlife Beach - Hostel', 'Sakhu', 'Phuket'),
('T.Y. Airport Inn', 'Sakhu', 'Phuket'),
('Bambooraya Villa', 'Ratsada', 'Phuket'),
('Three Monkeys Bungalows Koh Yao Noi', 'Phuket', 'Phuket'),
('Rassada Place', 'Phuket Town', 'Phuket'),
('OYO 792 Omsaga Phuket Hotel', 'Ratsada', 'Phuket'),
('T-House', 'Phuket', 'Phuket'),
('Phuket Ecozy Hotel', 'Kathu', 'Phuket'),
('Lucky Loft Phuket', 'Phuket Town', 'Phuket'),
('Star Hotel Patong', 'Patong', 'Phuket'),
('Da Mario Hotel And Restaurant', 'Phuket', 'Phuket'),
('Dome Resort by Phuket9', 'Phuket', 'Phuket'),
('Pgs Hotels Casa Del Sol', 'Karon', 'Phuket'),
('Kata Minta Phuket', 'Kata', 'Phuket'),
('Pai Villa Phuket', 'Patong', 'Phuket'),
('Vivi Bungalows Resort', 'Rawai', 'Phuket'),
('Mood Mansion', 'Patong', 'Phuket'),
('Tyler Banpon', 'Si Sunthon', 'Phuket'),
('Vivace Hotel', 'Kamala', 'Phuket'),
('Royal Lee Resort & Spa', 'Sakhu', 'Phuket'),
('Niramaya Villa and Wellness', 'Phuket', 'Phuket'),
('Sun Globe Resort', 'Phuket', 'Phuket'),
('Onnicha Hotel', 'Phuket Town', 'Phuket'),
('M.U.DEN Patong Phuket Hotel', 'Patong', 'Phuket'),
('Tiger Hotel', 'Patong', 'Phuket'),
('OYO 861 Patong Dynasty Hotel', 'Patong', 'Phuket'),
('Art Patong Residence', 'Patong', 'Phuket'),
('Patong Heaven', 'Patong', 'Phuket'),
('The Royal Palm Beachfront', 'Patong', 'Phuket'),
('Lap Roi Karon Beachfront', 'Karon', 'Phuket'),
('KB Apartments 1 Karon Beach by PHR', 'Karon', 'Phuket'),
('The Happy Elephant Resort', 'Phuket Town', 'Phuket'),
('Anchan Resort at Bangtao Beach', 'Bang Tao', 'Phuket'),
('Janya Homestay', 'Chalong', 'Phuket'),
('Namadee House', 'Mai Khao', 'Phuket'),
('Pasai Beach Lodge', 'Phuket', 'Phuket'),
('Phuket Garden Home', 'Chalong', 'Phuket'),
('Rawai Guesthouse', 'Rawai', 'Phuket'),
('Dwell At Chalong Hill', 'Chalong', 'Phuket'),
('Phuket Jula Place', 'Chalong', 'Phuket'),
('The Aristo Seaview Hotel Patong', 'Patong', 'Phuket'),
('Triple Three Patong', 'Patong', 'Phuket'),
('Capital O806 Sira Grande Hotel and Spa', 'Patong', 'Phuket'),
('The Landmark Patong', 'Patong', 'Phuket'),
('The Elegant Patong', 'Patong', 'Phuket'),
('J Sweet Dream Boutique Patong', 'Patong', 'Phuket'),
('Arita House', 'Patong', 'Phuket'),
('I-kroon Café & Hotel', 'Patong', 'Phuket'),
('Small Shells Hotel Phuket', 'Patong', 'Phuket'),
('Kata Blue Sea Resort', 'Kata', 'Phuket'),
('Aloha Residence', 'Karon', 'Phuket'),
('Secret Cliff Villa', 'Karon', 'Phuket'),
('Tananza Resort and Homestay Phuket', 'Thalang', 'Phuket'),
('Villa Elisabeth', 'Kata', 'Phuket'),
('Baan Armeen Cottage', 'Choeng Thale', 'Phuket'),
('Naithon Beach Mansion', 'Thalang', 'Phuket'),
('Phuket Sirinapha Resort', 'Sakhu', 'Phuket'),
('Blue Voyage Thailand', 'Mai Khao', 'Phuket'),
('Koh Yao Chukit Dachanan Resort', 'Phuket', 'Phuket'),
('Chalong Stay Well by Palai Seafood', 'Chalong', 'Phuket'),
('Fiji Palms Phuket', 'Phuket Town', 'Phuket'),
('Pool Access Hotel Near Fitness Street soi Ta Iad', 'Chalong', 'Phuket'),
('Phumundra Resort', 'Phuket Town', 'Phuket'),
('Falang Paradise', 'Chalong', 'Phuket'),
('Candy House', 'Phuket', 'Phuket'),
('Raha Grand Hotel Patong', 'Patong', 'Phuket'),
('Mėnulis Coolly House Patong', 'Patong', 'Phuket'),
('Niku Guesthouse', 'Patong', 'Phuket'),
('Orange Hotel', 'Phuket', 'Phuket'),
('Beam House', 'Patong', 'Phuket'),
('The Gallery Hotel', 'Rawai', 'Phuket'),
('Ricos Hotel Patong', 'Patong', 'Phuket'),
('Karon Sea Side', 'Karon', 'Phuket'),
('Pro Andaman Place', 'Karon', 'Phuket'),
('Your Place Inn', 'Karon', 'Phuket'),
('ZEN Villa', 'Rawai', 'Phuket'),
('OYO 888 Apinya''s Place Karon', 'Karon', 'Phuket'),
('Assada Boutique Hotel', 'Phuket Town', 'Phuket'),
('Kata Green Beach Hotel', 'Kata', 'Phuket'),
('Black Pearl Patong Beach', 'Patong', 'Phuket'),
('Again at Naiharn Beach Resort', 'Rawai', 'Phuket'),
('Clear House Resort', 'Kamala', 'Phuket'),
('Na Kamala Homestay', 'Kamala', 'Phuket'),
('Nua Tone Resort & Cafe', 'Bang Tao', 'Phuket'),
('Bangtao Mango House - Adults Only', 'Bang Tao', 'Phuket'),
('Bang Tidlay Koh Yao Noi', 'Phuket', 'Phuket'),
('Green Mountain Resort Koh Yao', 'Phuket', 'Phuket'),
('Dusit Naka Place', 'Wichit', 'Phuket'),
('Blue Carina Inn 2', 'Phuket Town', 'Phuket'),
('Summer Breeze Inn Hotel', 'Phuket Town', 'Phuket'),
('Tawee Garden and Resort', 'Phuket Town', 'Phuket'),
('Phuket Kata Resotel', 'Kata', 'Phuket'),
('Escape De Phuket Hotel', 'Ratsada', 'Phuket'),
('Cloud 19 Panwa', 'Phuket Town', 'Phuket'),
('Pier 42 Boutique Resort & Spa', 'Chalong', 'Phuket'),
('Two Color Patong', 'Patong', 'Phuket'),
('Times Sri Boutique Hotel', 'Patong', 'Phuket'),
('The Coconut Resort', 'Patong', 'Phuket'),
('Maikhao Residence', 'Mai Khao', 'Phuket'),
('Lemon Tree Naturist Resort Naiharn Beach', 'Rawai', 'Phuket'),
('Frutta Hostel', 'Patong', 'Phuket'),
('OYO 1134 Baan Zarn Guesthouse', 'Patong', 'Phuket'),
('The Orchid Hotel Kalim Bay Resort', 'Patong', 'Phuket'),
('OYO 1074 Fin Hostel', 'Kata', 'Phuket'),
('Fin Hostel Co Working', 'Kata', 'Phuket'),
('Baan Bua Estate by Tropiclook', 'Rawai', 'Phuket'),
('Up2you Hotel', 'Patong', 'Phuket'),
('Baanmee Phuket Sha Plus', 'Chalong', 'Phuket'),
('Phoomjai House', 'Chalong', 'Phuket'),
('Andaman House', 'Patong', 'Phuket'),
('OYO 1007 Vech Guesthouse', 'Patong', 'Phuket'),
('Baan Rosa', 'Choeng Thale', 'Phuket'),
('Oceanstone Laguna Phuket', 'Choeng Thale', 'Phuket'),
('Jantra Residence by Chinocollection', 'Kathu', 'Phuket'),
('Taj Phuket Inn', 'Kathu', 'Phuket'),
('The Beachfront Hotel Phuket', 'Rawai', 'Phuket'),
('Swissotel Resort Phuket Patong Beach', 'Patong', 'Phuket'),
('Chalong Boutique Inn', 'Karon', 'Phuket'),
('Baan Yuyen Karon Guesthouse', 'Karon', 'Phuket'),
('OYO 295 Salamat Bangtao', 'Bang Tao', 'Phuket'),
('Title Residencies by Phuket Apartments', 'Sakhu', 'Phuket'),
('Naiyang Tour Room For Rent', 'Nai Yang', 'Phuket'),
('Baan Panwa Resort&Spa', 'Phuket Town', 'Phuket'),
('Sea Sun Sand Resort & Spa', 'Patong', 'Phuket'),
('Oceana Resort Phuket', 'Kamala', 'Phuket'),
('Koh Yao Heaven Beach Resort', 'Phuket', 'Phuket'),
('Royal Crown Hotel & Palm Spa Resort', 'Patong', 'Phuket'),
('Chalong Beach Hotel Phuket', 'Rawai', 'Phuket'),
('Araya Beach Hotel Patong', 'Patong', 'Phuket'),
('Time Out Hotel Beach Front', 'Patong', 'Phuket'),
('Hyton Leelavadee', 'Patong', 'Phuket'),
('Baan Vanida Garden Resort', 'Karon', 'Phuket'),
('Ratana Apart-Hotel at Kamala', 'Kamala', 'Phuket'),
('Phuket"', 'Phuket', 'Phuket'),
('Beachfront Phuket', 'Choeng Thale', 'Phuket'),
('Add Plus Hotel & Spa', 'Patong', 'Phuket'),
('Madam Inn Patong', 'Patong', 'Phuket'),
('Coco Palace Resort', 'Rawai', 'Phuket'),
('Surin Sunset Hotel', 'Surin', 'Phuket'),
('Connect Guesthouse', 'Patong', 'Phuket'),
('Kata Silver Sand Hotel', 'Kata', 'Phuket'),
('Bangtao Beach Garden', 'Bang Tao', 'Phuket'),
('White Sand Phuket Residence', 'Phuket Town', 'Phuket'),
('Phuket7-inn Hotel', 'Phuket Town', 'Phuket'),
('Jang Resort', 'Patong', 'Phuket'),
('Karon Whale Resort', 'Karon', 'Phuket'),
('Outrigger Laguna Phuket Resort Villas', 'Bang Tao', 'Phuket'),
('SM Resort Phuket', 'Patong', 'Phuket'),
('Ricos Bungalows Kata', 'Kata', 'Phuket'),
('Tri Trang Beach Resort', 'Patong', 'Phuket'),
('Tha Khao Bay View', 'Phuket', 'Phuket'),
('Phuket Marine Poshtel - Hostel', 'Chalong', 'Phuket'),
('Yindee Residence', 'Patong', 'Phuket'),
('Bayshore Ocean View', 'Patong', 'Phuket'),
('Tiger Inn', 'Patong', 'Phuket'),
('Action Point Fitness Resort', 'Rawai', 'Phuket'),
('Smile House Karon', 'Karon', 'Phuket'),
('Metadee Elite - SHA Extra Plus', 'Kata', 'Phuket'),
('Kamala Regent Phuket Serviced Apartment', 'Kamala', 'Phuket'),
('The Mareeya Place', 'Kamala', 'Phuket'),
('At The Tree Phuket', 'Rawai', 'Phuket'),
('Chandara Resort & Spa Phuket', 'Pa Klok', 'Phuket'),
('Phuthara Mansion', 'Phuket Town', 'Phuket'),
('Omsaga Phuket Hotel', 'Ratsada', 'Phuket'),
('T Resort Palai', 'Chalong', 'Phuket'),
('At Phuket Inn Patong Beach', 'Patong', 'Phuket'),
('ELLA Bar, Bistro & Bed', 'Phuket', 'Phuket'),
('Charcoal Panwa Beach', 'Wichit', 'Phuket'),
('I AM O''TEL PATONG', 'Patong', 'Phuket'),
('Coconoi Residence', 'Rawai', 'Phuket'),
('Lespalm Taraburi Pool Villa', 'Phuket', 'Phuket'),
('Bann Anattaya Koh Yao Noi', 'Phuket', 'Phuket'),
('Alpina Phuket Nalina Resort & Spa', 'Phuket', 'Phuket'),
('OYO 232 Patong City Hometel', 'Patong', 'Phuket'),
('Relaxing House Koh Yao Yai', 'Phuket', 'Phuket'),
('Pachumas Mansion', 'Karon', 'Phuket'),
('U Tai Tip Guest House', 'Patong', 'Phuket'),
('Hotel DSure Patong', 'Patong', 'Phuket'),
('OYO 472 Tang Cheng Holiday Hotel', 'Phuket', 'Phuket'),
('Wayla Villa Maikhao Beach', 'Mai Khao', 'Phuket'),
('Komaree Mansion', 'Patong', 'Phuket'),
('SB Park Mansion', 'Kathu', 'Phuket'),
('B-Lay Tong Beach Resort', 'Patong', 'Phuket'),
('In On The Beach', 'Karon', 'Phuket'),
('Bussarin Mansion', 'Phuket', 'Phuket'),
('Squareone - Hostel', 'Patong', 'Phuket'),
('Baan Coconut', 'Choeng Thale', 'Phuket'),
('Phumi Resort', 'Thep Krasattri', 'Phuket'),
('Chaiyo Resort', 'Phuket Town', 'Phuket'),
('Calypso Patong Hotel', 'Patong', 'Phuket'),
('Baan Suan Leela', 'Sakhu', 'Phuket'),
('Lavender Patong Hotel', 'Patong', 'Phuket'),
('I Dee Hotel Patong', 'Patong', 'Phuket'),
('KB Apartments 3 Karon Beach by PHR', 'Karon', 'Phuket'),
('I Am Residence', 'Patong', 'Phuket'),
('Condo in Kata in Ozonec- Unit D618', 'Kata', 'Phuket'),
('The Kara Pool Villa', 'Sakhu', 'Phuket'),
('TP House@Naka', 'Phuket Town', 'Phuket'),
('Hotel Orchid Residence', 'Patong', 'Phuket'),
('Serenity Grand Seaview Suite', 'Rawai', 'Phuket'),
('Sonya Residence', 'Patong', 'Phuket'),
('Popeyes Hostel Coffeeshop and Beer Bar', 'Patong', 'Phuket'),
('Vacation Time House', 'Thalang', 'Phuket'),
('Ban Elephant Blanc Bungalow', 'Karon', 'Phuket'),
('Phuket Paradiso Hotel', 'Chalong', 'Phuket'),
('Awana Villa Resort Yaonoi', 'Phuket', 'Phuket'),
('Rawai Princess Hotel', 'Rawai', 'Phuket'),
('Koola Guesthouse', 'Phuket', 'Phuket'),
('Yamin Seaview Hotel', 'Phuket Town', 'Phuket'),
('KRAAM Silhouette Hotel and Cafe Phuket', 'Rawai', 'Phuket'),
('Jinta Andaman', 'Kata', 'Phuket'),
('The Silk Hill Hotel', 'Patong', 'Phuket'),
('Hill Side Hotel', 'Patong', 'Phuket'),
('One World One Home Naiharn Hotel', 'Rawai', 'Phuket'),
('Oceana Kamala Resort', 'Kamala', 'Phuket'),
('Baan Norkna Bangtao', 'Bang Tao', 'Phuket'),
('The Touch Green Naiyang Hotel & Fitness', 'Nai Yang', 'Phuket'),
('Pennapa Chalet', 'Phuket', 'Phuket'),
('Modern Place Patong Beach', 'Patong', 'Phuket'),
('Arun Seaview', 'Phuket Town', 'Phuket'),
('RangRong Hotel', 'Patong', 'Phuket'),
('Pineapple Guesthouse', 'Karon', 'Phuket'),
('The Umbrella House', 'Kamala', 'Phuket'),
('Baannueng', 'Kathu', 'Phuket'),
('Tharaburi at Panwa', 'Phuket Town', 'Phuket'),
('Condo in Karon in Chic Condo - Unit A609', 'Karon', 'Phuket'),
('Angelina Guesthouse', 'Patong', 'Phuket'),
('The Regent Phuket Serviced Apartment Kamala Beach', 'Kamala', 'Phuket'),
('Phant at Thalang Service Apartment', 'Thep Krasattri', 'Phuket'),
('Andaman Place@baandon', 'Phuket Town', 'Phuket'),
('BJ&Radisson Sea View Resort Koh Yao Yai', 'Phuket', 'Phuket'),
('Anchan Private Pool Villas', 'Chalong', 'Phuket'),
('OYO 1162 Chalong Home Place', 'Chalong', 'Phuket'),
('Natural Mystic Patong Residence', 'Patong', 'Phuket'),
('Condo in Karon in Chic Condo - Unit A108', 'Karon', 'Phuket'),
('Orchid Hotel and Spa', 'Patong', 'Phuket'),
('JJ Guesthouse', 'Phuket', 'Phuket'),
('Condo in Kata in Ozone - A604', 'Kata', 'Phuket'),
('Mayan Apartment', 'Phuket', 'Phuket'),
('The Bread Basket', 'Kathu', 'Phuket'),
('The Sunflower Holiday Hostel', 'Choeng Thale', 'Phuket'),
('SunSeaSand Hotel', 'Patong', 'Phuket'),
('Reuan Thai Villa', 'Patong', 'Phuket'),
('The Wave Patong Boutique Hotel', 'Patong', 'Phuket'),
('Hemingway''s Hotel', 'Patong', 'Phuket'),
('Sino Hostel Kata', 'Kata', 'Phuket'),
('Surin Loft by Holiplanet', 'Surin', 'Phuket'),
('The Way Phuket Resort', 'Thalang', 'Phuket'),
('My Friend''s House', 'Karon', 'Phuket'),
('May House Karon Beach', 'Karon', 'Phuket'),
('Kata Bai D Inn', 'Kata', 'Phuket'),
('Naiyang Cottage', 'Nai Yang', 'Phuket'),
('Bangtao Corner', 'Bang Tao', 'Phuket'),
('Thuan Resort', 'Rawai', 'Phuket'),
('Sabina Guesthouse', 'Kamala', 'Phuket'),
('Muchshima House', 'Bang Tao', 'Phuket'),
('Dwell Phuket Airport', 'Sakhu', 'Phuket'),
('Kata S.T House 2', 'Kata', 'Phuket'),
('Hi Karon Beach Hotel', 'Karon', 'Phuket'),
('Big Buddha Hillside Hotel', 'Chalong', 'Phuket'),
('Crest Pool Villas', 'Patong', 'Phuket'),
('My Style Resort Hotel', 'Patong', 'Phuket'),
('Lamai Guesthouse', 'Patong', 'Phuket'),
('The Title Condo by TropicLook', 'Rawai', 'Phuket'),
('Arch39 Phuket Beach Front', 'Chalong', 'Phuket'),
('Sugar and Spice Inn', 'Kata', 'Phuket'),
('Holiday Resort Ko Yao', 'Phuket', 'Phuket'),
('The Oceanic Sportel', 'Phuket Town', 'Phuket'),
('The LifeCo Phuket Well-Being Detox Center', 'Sakhu', 'Phuket'),
('Bonus Bungalow', 'Chalong', 'Phuket'),
('Natika Apartment', 'Patong', 'Phuket'),
('Smile Home', 'Patong', 'Phuket'),
('Patong Beach Hotel', 'Patong', 'Phuket'),
('OYO 389 Sira Boutique Residence', 'Patong', 'Phuket'),
('W Hostel', 'Mai Khao', 'Phuket'),
('Pipikuku Hotel & Restaurant', 'Patong', 'Phuket'),
('Garden Phuket Phuket', 'Phuket', 'Phuket'),
('OYO 503 Phuket Numnoi - Hostel', 'Choeng Thale', 'Phuket'),
('Patong Bay Inn', 'Patong', 'Phuket'),
('Heaven House', 'Patong', 'Phuket'),
('MONTANA Hotel & Hostel Phuket', 'Karon', 'Phuket'),
('Happy Eight Resort Phuket', 'Rawai', 'Phuket'),
('Prayai Changthai Resort', 'Chalong', 'Phuket'),
('bistrot helene', 'Kata', 'Phuket'),
('Baan Mai Beachfront Phuket Lone Island', 'Rawai', 'Phuket'),
('Bodega Patong Phuket - Hostel', 'Patong', 'Phuket'),
('Baantonkhao Kata Beach', 'Kata', 'Phuket'),
('The Way Patong Hotel', 'Patong', 'Phuket'),
('Ramada by Wyndham Phuket Southsea', 'Karon', 'Phuket'),
('The Pace Phuket Resort', 'Rawai', 'Phuket'),
('Arita Hotel', 'Patong', 'Phuket'),
('The Melody Phuket Hotel', 'Karon', 'Phuket'),
('Mirage Express Patong Phuket Hotel', 'Patong', 'Phuket'),
('Hiran Residence', 'Kathu', 'Phuket'),
('Panwa Boutique Beachfront', 'Wichit', 'Phuket'),
('Baan Sudarat', 'Patong', 'Phuket'),
('Rico''s Patong Residence', 'Patong', 'Phuket'),
('Ra Residence Phuket', 'Chalong', 'Phuket'),
('The One Cozy Vacation Residence', 'Phuket Town', 'Phuket'),
('Le Tanjong House', 'Patong', 'Phuket'),
('Splash Beach Villa Resort', 'Mai Khao', 'Phuket'),
('Raya Rawai Place', 'Rawai', 'Phuket'),
('Phuket Airport Villa', 'Sakhu', 'Phuket'),
('MT Hotel Patong', 'Patong', 'Phuket'),
('Tyler Cherngtalay', 'Choeng Thale', 'Phuket'),
('Living Residence Phuket', 'Phuket', 'Phuket'),
('D C Patong', 'Patong', 'Phuket'),
('Rattana Beach Hotel', 'Karon', 'Phuket'),
('Sawasdee Orange Phuket Guest House', 'Rawai', 'Phuket'),
('The Regent Hotel Kamala Beach', 'Kamala', 'Phuket'),
('Kata S.T. House', 'Kata', 'Phuket'),
('Baan Kalaya Garden', 'Thep Krasattri', 'Phuket'),
('Sala Bua Room Karon', 'Karon', 'Phuket'),
('Maikhao Home Garden Bungalow', 'Mai Khao', 'Phuket'),
('Casa Bella Phuket', 'Chalong', 'Phuket'),
('NB House', 'Karon', 'Phuket'),
('Serenity Resort & Residences Phuket', 'Rawai', 'Phuket'),
('Green Island Guesthouse', 'Karon', 'Phuket'),
('Fong Kaew and Baan Nang Fa Guesthouse', 'Patong', 'Phuket'),
('Studio Deluxe Avec Services Hôteliers - Adults Only', 'Rawai', 'Phuket'),
('The Chalet Phuket Resort', 'Phuket Town', 'Phuket'),
('BGW Phuket - Hostel', 'Patong', 'Phuket'),
('Baan Yamu Residences', 'Thalang', 'Phuket'),
('Neptuna Kata Hotel', 'Kata', 'Phuket'),
('Nasa Hotel', 'Phuket', 'Phuket'),
('Days Inn by Wyndham Patong Beach Phuket', 'Patong', 'Phuket'),
('Serene Villa', 'Chalong', 'Phuket'),
('Surintra Boutique Resort', 'Surin', 'Phuket'),
('Rawai Apartment', 'Rawai', 'Phuket'),
('Golden Manora Hotel Bangtao Beach', 'Bang Tao', 'Phuket'),
('OYO 358 Rattana Residence Thalang', 'Thalang', 'Phuket'),
('Ideo Phuket Hotel', 'Sakhu', 'Phuket'),
('Tall Tree Kata Phuket - Hostel', 'Kata', 'Phuket'),
('Benyada Lodge', 'Surin', 'Phuket'),
('Sandy House Rawai', 'Rawai', 'Phuket'),
('Ocean Pie Phuket', 'Rawai', 'Phuket'),
('Phuket Siam Villas', 'Chalong', 'Phuket'),
('JJ Residence Phuket Town', 'Phuket Town', 'Phuket'),
('Art Mansion Patong Hotel', 'Patong', 'Phuket'),
('Karon Princess Hotel', 'Karon', 'Phuket'),
('PKL Residence', 'Patong', 'Phuket'),
('Lucky Buako Hotel Patong', 'Patong', 'Phuket'),
('Z&Z House', 'Rawai', 'Phuket'),
('Tulip Inn', 'Patong', 'Phuket'),
('Kata Sun Beach Hotel', 'Kata', 'Phuket'),
('Silla Villa', 'Karon', 'Phuket'),
('LaXenia', 'Karon', 'Phuket'),
('Laguna Holiday Club Phuket Resort', 'Choeng Thale', 'Phuket'),
('Shade House - Phuket Downtown', 'Kathu', 'Phuket'),
('Beau and Blonde House Kamala', 'Kamala', 'Phuket'),
('Turtle Rooms', 'Si Sunthon', 'Phuket'),
('Siralanna Phuket', 'Patong', 'Phuket'),
('SP House Phuket', 'Karon', 'Phuket'),
('Kata Station', 'Kata', 'Phuket'),
('Bests village & villa', 'Chalong', 'Phuket'),
('Soul Villas By The Beach - Phuket', 'Wichit', 'Phuket'),
('Q Victory Patong', 'Patong', 'Phuket'),
('Hasanah Guesthouse', 'Bang Tao', 'Phuket'),
('Palmview Resort', 'Patong', 'Phuket'),
('Phuket View Coffee and Resort', 'Chalong', 'Phuket'),
('Ratana Hill Patong', 'Patong', 'Phuket'),
('NR Nanai Patong', 'Patong', 'Phuket'),
('Phuket Kata Resotel', 'Kata', 'Phuket'),
('Floraville Phuket Resort', 'Chalong', 'Phuket'),
('Ruan Mai Naiyang Beach Resort', 'Nai Yang', 'Phuket'),
('K.L.Apartment', 'Rawai', 'Phuket'),
('Lamai Apartment', 'Phuket', 'Phuket'),
('Mr. T Kamala Room', 'Kamala', 'Phuket'),
('Amici Miei Hotel', 'Phuket', 'Phuket'),
('Patong V Hotel', 'Patong', 'Phuket'),
('Dream Phuket Hotel & Spa', 'Phuket', 'Phuket'),
('The Lantern Hostel and SPA', 'Chalong', 'Phuket'),
('Central Residences', 'Wichit', 'Phuket'),
('Recenta Phuket Suanluang', 'Phuket Town', 'Phuket'),
('Tina Boutique Resort', 'Thep Krasattri', 'Phuket'),
('J and N Mansion 2', 'Patong', 'Phuket'),
('Nature Pine Residence', 'Rawai', 'Phuket'),
('Pimrada Hotel', 'Patong', 'Phuket'),
('Dlux Condominium', 'Chalong', 'Phuket'),
('Babylon Pool Villas', 'Rawai', 'Phuket'),
('CAPITAL O75345 Praewa Villas Naiyang Phuket', 'Nai Yang', 'Phuket'),
('KB Apartments 2 Karon Beach by PHR', 'Karon', 'Phuket'),
('Phuket Campground', 'Mai Khao', 'Phuket'),
('Fern House Retreat', 'Chalong', 'Phuket'),
('Naiyang Discovery Beach Resort', 'Nai Yang', 'Phuket'),
('Again Thaicharm House at Patong Beach', 'Patong', 'Phuket'),
('RK Guesthouse', 'Patong', 'Phuket'),
('Cview boutique', 'Rawai', 'Phuket'),
('Be Leaf Resort', 'Thep Krasattri', 'Phuket'),
('Anayara Luxury Retreat Panwa Resort', 'Phuket Town', 'Phuket'),
('Tuna Resort', 'Rawai', 'Phuket'),
('Angus O''Tool''s Irish Pub Guesthouse', 'Karon', 'Phuket'),
('Memory Boutique Hotel', 'Patong', 'Phuket'),
('Ruan Mai Sang Ngam Resort', 'Sakhu', 'Phuket'),
('Swiss House', 'Patong', 'Phuket'),
('Majestic Villas Phuket', 'Rawai', 'Phuket'),
('Eden Resort & Villas', 'Patong', 'Phuket'),
('The Orchid House', 'Kata', 'Phuket'),
('Nan inn Bungalow', 'Karon', 'Phuket'),
('Lime Hotel', 'Patong', 'Phuket'),
('ETK Patong', 'Patong', 'Phuket'),
('Sleep Box Patong - Hostel', 'Patong', 'Phuket'),
('Coral Inn', 'Karon', 'Phuket'),
('The Regent Resort Phuket', 'Kamala', 'Phuket'),
('Khao Oat Airport', 'Mai Khao', 'Phuket'),
('Baan Suan Villas Resort', 'Chalong', 'Phuket'),
('Pumeria Resort Phuket', 'Bang Tao', 'Phuket'),
('OYO 885 You And Me House', 'Patong', 'Phuket'),
('Baan Suay Hotel Resort', 'Karon', 'Phuket'),
('OYO 343 Wanna Marine', 'Patong', 'Phuket'),
('Hop On Phuket', 'Mai Khao', 'Phuket'),
('99 Residence', 'Patong', 'Phuket'),
('Kamala Cool 2', 'Kamala', 'Phuket'),
('Phu NaNa Boutique Hotel', 'Phuket Town', 'Phuket'),
('Oceana Sea View Apartments by Alexanders', 'Kamala', 'Phuket'),
('Monaburi Hotel', 'Rawai', 'Phuket'),
('Oneloft Hotel', 'Karon', 'Phuket'),
('Vipa House Phuket', 'Rawai', 'Phuket'),
('S2 Airport Residence', 'Nai Yang', 'Phuket'),
('D.J. House', 'Patong', 'Phuket'),
('Ice Kamala Beach Hotel', 'Kamala', 'Phuket'),
('Praew Mansion', 'Kamala', 'Phuket'),
('Amala Grand Bleu Resort Hilltops', 'Kamala', 'Phuket'),
('Karon Living Room', 'Karon', 'Phuket'),
('2 Home Resort', 'Chalong', 'Phuket'),
('Sea Hills Resort', 'Patong', 'Phuket'),
('TT Naiyang Beach Phuket', 'Nai Yang', 'Phuket'),
('Phusita House 3', 'Patong', 'Phuket'),
('Khaleej Mass Hotel Patong', 'Patong', 'Phuket'),
('Serenity Lakeside Resort', 'Kathu', 'Phuket'),
('Malin Patong Hotel', 'Patong', 'Phuket'),
('Sweet Dreams', 'Patong', 'Phuket'),
('Hotel Grand Orchid Inn', 'Patong', 'Phuket'),
('Rawai Grand House', 'Rawai', 'Phuket'),
('Good Day Phuket', 'Phuket Town', 'Phuket'),
('Lemonade Phuket', 'Chalong', 'Phuket'),
('Isayarada Apartment', 'Thep Krasattri', 'Phuket'),
('Jasmine Village', 'Rawai', 'Phuket'),
('Pensiri House', 'Nai Yang', 'Phuket'),
('Sun Shine Patong', 'Patong', 'Phuket'),
('Sabai Corner Bungalows', 'Phuket', 'Phuket'),
('Blue Sky Residence', 'Patong', 'Phuket'),
('Kata Interhouse Resort by Haii Collection', 'Kata', 'Phuket'),
('Panda Hotel（Patong Beach）', 'Patong', 'Phuket'),
('Rat Villa', 'Pa Klok', 'Phuket'),
('Amin Resort', 'Choeng Thale', 'Phuket'),
('Hotel de Karon', 'Karon', 'Phuket'),
('The Green Mansion', 'Patong', 'Phuket'),
('Le Desir Resortel', 'Chalong', 'Phuket'),
('Phu-Kamala', 'Kamala', 'Phuket'),
('Hotel De Ratt', 'Phuket Town', 'Phuket'),
('The Fusion Resort', 'Chalong', 'Phuket'),
('Patong Rai Rom Yen Resort SHA', 'Patong', 'Phuket'),
('Lemon House', 'Patong', 'Phuket'),
('Supicha pool access hotel', 'Phuket', 'Phuket'),
('The Residence Resort & Spa Retreat', 'Choeng Thale', 'Phuket'),
('Phuket La Siesta', 'Rawai', 'Phuket'),
('Magnific Patong', 'Patong', 'Phuket'),
('Happy Cottages Phuket', 'Chalong', 'Phuket'),
('Baan SS Karon', 'Karon', 'Phuket'),
('Ma Maison Phuket', 'Bang Tao', 'Phuket'),
('N&N HOUSE Laem Hin', 'Phuket Town', 'Phuket'),
('Baan Kim Lian Sha', 'Phuket Town', 'Phuket'),
('Naya Bungalow', 'Rawai', 'Phuket'),
('The Snug Airportel', 'Sakhu', 'Phuket'),
('Surin Bay Inn', 'Surin', 'Phuket'),
('Ruenthai Boutique', 'Nai Yang', 'Phuket'),
('Phoenix Grand Hotel', 'Patong', 'Phuket'),
('Louis'' Runway View Hotel', 'Mai Khao', 'Phuket'),
('Holiday Home Patong', 'Patong', 'Phuket'),
('BE Baan Paradise Hotel', 'Kathu', 'Phuket'),
('Blue Canyon Country Club', 'Mai Khao', 'Phuket'),
('Kata Leaf Resort', 'Kata', 'Phuket'),
('Eat n Sleep', 'Phuket Town', 'Phuket'),
('Safari Beach Hotel', 'Patong', 'Phuket'),
('Peace Blue Naiharn Naturist Resort Phuket', 'Rawai', 'Phuket'),
('Sunset Mansion', 'Patong', 'Phuket'),
('The Palms Residence', 'Kathu', 'Phuket'),
('Duangjai Residence', 'Phuket', 'Phuket'),
('Naiya Buree Boutique Resort', 'Rawai', 'Phuket'),
('Grace Patong Hotel', 'Patong', 'Phuket'),
('VII HOUSE RAWAI PHUKET', 'Rawai', 'Phuket'),
('The Chic Patong', 'Patong', 'Phuket'),
('Patong Signature Boutique Hotel', 'Patong', 'Phuket'),
('Splendid Sea View Resort', 'Karon', 'Phuket'),
('Bangtao Beach Chalet', 'Bang Tao', 'Phuket'),
('Cocoon Deva Hotel', 'Patong', 'Phuket'),
('Phoenix Hotel Karon Beach', 'Karon', 'Phuket'),
('Chez Charly Bungalow', 'Sakhu', 'Phuket'),
('Canal Resort', 'Thalang', 'Phuket'),
('Mission Hills Phuket Golf Resort', 'Pa Klok', 'Phuket'),
('Lokal Phuket', 'Patong', 'Phuket'),
('Meir Jarr Hotel', 'Patong', 'Phuket'),
('Prince Edouard Apartment & Resort', 'Patong', 'Phuket'),
('The Baray Villa by Sawasdee Village', 'Kata', 'Phuket'),
('Sugar Palm Grand Hillside', 'Karon', 'Phuket'),
('Hemingways Silk Hotel', 'Patong', 'Phuket'),
('Outdoor Inn Kata Hotel', 'Kata', 'Phuket'),
('On Hotel Phuket', 'Karon', 'Phuket'),
('Thai Modern Resort & Spa', 'Chalong', 'Phuket'),
('Mangosteen Ayurveda & Wellness Resort', 'Rawai', 'Phuket'),
('ChillHub Hostel', 'Bang Tao', 'Phuket'),
('The Casita Phuket', 'Mai Khao', 'Phuket'),
('KK - Karon Kata Boutique Hotel', 'Kata', 'Phuket'),
('The Par Phuket', 'Kathu', 'Phuket'),
('Casa Brazil Homestay & Gallery', 'Karon', 'Phuket'),
('G1 Touch Blue Sky', 'Kamala', 'Phuket'),
('Vech Guesthouse Patong', 'Patong', 'Phuket'),
('Boomerang Village Resort Kata', 'Kata', 'Phuket'),
('Dee Homestay', 'Pa Klok', 'Phuket'),
('Kata Beach Studio', 'Kata', 'Phuket'),
('Austrian Garden Hotel Patong', 'Patong', 'Phuket'),
('Martin''s Swiss Guesthouse', 'Patong', 'Phuket'),
('Dan''s Koyao Retreat', 'Phuket', 'Phuket'),
('iCheck inn Residences Patong', 'Patong', 'Phuket'),
('Neptuna Hotel by Maduzi', 'Patong', 'Phuket'),
('P.S. Hotel -SHA Plus', 'Patong', 'Phuket'),
('Lanting House Phuket', 'Patong', 'Phuket'),
('Choophorn House', 'Karon', 'Phuket'),
('Terminal 58', 'Sakhu', 'Phuket'),
('Laguna Villas Boutique Hotel', 'Laguna', 'Phuket'),
('The Elysium Residence', 'Chalong', 'Phuket'),
('Rabbit Mansion Patong Hotel', 'Patong', 'Phuket'),
('Kata Noi Resort', 'Kata', 'Phuket'),
('BS Airport at Phuket', 'Nai Yang', 'Phuket'),
('Backpacker Street Airport Place', 'Sakhu', 'Phuket'),
('Di Pantai Boutique Beach Resort', 'Patong', 'Phuket'),
('Andaman Place', 'Phuket Town', 'Phuket'),
('Thai Siam', 'Patong', 'Phuket'),
('Sugar Ohana Poshtel', 'Kata', 'Phuket'),
('Be Live Residence', 'Thep Krasattri', 'Phuket'),
('Must Sea Hotel Kata', 'Kata', 'Phuket'),
('Amalthea Hotel', 'Patong', 'Phuket'),
('The Gallery Hotel Nai Harn', 'Rawai', 'Phuket'),
('Kanya Cozy Bungalows Kata Beach', 'Kata', 'Phuket'),
('Ginis Beach Resort', 'Kamala', 'Phuket'),
('Cocoville Phuket Resort', 'Chalong', 'Phuket'),
('Blue Carina Hotel', 'Phuket Town', 'Phuket'),
('The Mantra Hotel', 'Kata', 'Phuket'),
('Phuket Racha at Kata Homestay', 'Kata', 'Phuket'),
('Baramee Resortel', 'Patong', 'Phuket'),
('Kata Tranquil Villa', 'Kata', 'Phuket'),
('1715 House & Caff Resort Phuket', 'Rawai', 'Phuket'),
('Siray Green Resort', 'Ratsada', 'Phuket'),
('Leam Sai Bungalows Koh Yao Noi', 'Phuket', 'Phuket'),
('Ron''s Bungalow', 'Choeng Thale', 'Phuket'),
('Karon Sino House', 'Karon', 'Phuket'),
('Koyao Bay Pavilions', 'Phuket', 'Phuket'),
('Naiyang Seaview Place', 'Nai Yang', 'Phuket'),
('Swiss Villas Panoramic', 'Patong', 'Phuket'),
('TAJH Pool Villas', 'Chalong', 'Phuket'),
('Tann Anda Resort', 'Thalang', 'Phuket'),
('Patong Platinums', 'Patong', 'Phuket'),
('Black Pearl Patong Beach', 'Patong', 'Phuket'),
('Villa Sonata Phuket', 'Chalong', 'Phuket'),
('Unotel Karon Beach', 'Karon', 'Phuket'),
('Prime Town - Posh & Port Hotel Phuket', 'Phuket Town', 'Phuket'),
('Dfeel House', 'Patong', 'Phuket'),
('Bougainvillea Terrace House', 'Karon', 'Phuket'),
('Anchanlina Hotel', 'Chalong', 'Phuket'),
('Baan Taranya Koh Yao Yai', 'Phuket', 'Phuket'),
('Sue at Cozy Guesthouse', 'Phuket', 'Phuket'),
('D Varee Mai Khao Beach', 'Mai Khao', 'Phuket'),
('ibis Phuket Kata', 'Kata', 'Phuket'),
('Hotel COCO Phuket Bangtao', 'Bang Tao', 'Phuket'),
('T-Villa Phuket Nai Yang Beach', 'Nai Yang', 'Phuket'),
('Royal Thai Villas Phuket', 'Rawai', 'Phuket'),
('Patong Princess Hotel', 'Patong', 'Phuket'),
('9 Hornbills Tented Camp', 'Phuket', 'Phuket'),
('Nanai 2 Residence Patong', 'Patong', 'Phuket'),
('Best Western Premier Bangtao Beach Resort & Spa', 'Bang Tao', 'Phuket'),
('Beachwalk Patong', 'Patong', 'Phuket'),
('Kamala Beach Residence', 'Kamala', 'Phuket'),
('Baan Pron Phateep', 'Patong', 'Phuket'),
('Big Boys'' Bed & Burger', 'Patong', 'Phuket'),
('77 Bangla Hotel', 'Patong', 'Phuket'),
('The Cove Phuket', 'Phuket Town', 'Phuket'),
('Freedom Kata', 'Kata', 'Phuket'),
('Thalang Resort', 'Si Sunthon', 'Phuket'),
('Le Piman Resort', 'Rawai', 'Phuket'),
('The Rubber Hotel', 'Thep Krasattri', 'Phuket'),
('Rayaburi Hotel Patong', 'Patong', 'Phuket'),
('Ya Nui Resort', 'Rawai', 'Phuket'),
('Baan Kongdee Sunset Resort', 'Karon', 'Phuket'),
('Chalong Princess Pool Villa Resort', 'Chalong', 'Phuket'),
('Naiyang Boutique Resort', 'Nai Yang', 'Phuket'),
('Kamala Resotel', 'Kamala', 'Phuket'),
('Jiraporn Hill Resort', 'Patong', 'Phuket'),
('Sungthong Kamala Beach Resort', 'Kamala', 'Phuket'),
('Simplitel', 'Karon', 'Phuket'),
('Am Surin Place', 'Surin', 'Phuket'),
('C&N Resort and Spa', 'Kathu', 'Phuket'),
('OYO 241 Ratana Hotel Sakdidet', 'Phuket', 'Phuket'),
('Thai Kamala Beach Front', 'Kamala', 'Phuket'),
('TIRAS Patong Beach Hotel', 'Patong', 'Phuket'),
('The Privilege Residences', 'Patong', 'Phuket'),
('Baan Sailom Resort', 'Karon', 'Phuket'),
('Baan Karon Resort', 'Karon', 'Phuket'),
('Airport Overnight Hotel', 'Mai Khao', 'Phuket'),
('Phuket Jungle Experience Resort', 'Karon', 'Phuket'),
('Break Point Hotel', 'Patong', 'Phuket'),
('Baan Krating Phuket Resort', 'Rawai', 'Phuket'),
('Mellow Space Boutique Rooms', 'Karon', 'Phuket'),
('Impress Resort', 'Thep Krasattri', 'Phuket'),
('Glur Phuket Patong Beach', 'Patong', 'Phuket'),
('P.S Hill Resort', 'Patong', 'Phuket'),
('Alphabeto Resort', 'Rawai', 'Phuket'),
('Phuket Gay Home Stay - Caters to Men', 'Kathu', 'Phuket'),
('Baan Waru Seaview', 'Phuket', 'Phuket'),
('B Happy Resort', 'Kamala', 'Phuket'),
('Norn Talay Surin Beach Phuket', 'Surin', 'Phuket'),
('Green House Phuket', 'Pa Klok', 'Phuket'),
('Patong Buri Resort', 'Patong', 'Phuket'),
('Siray House', 'Ratsada', 'Phuket'),
('Gu Hotel Patong', 'Patong', 'Phuket'),
('Kata Sea Host', 'Kata', 'Phuket'),
('Pai Tan Villas', 'Bang Tao', 'Phuket'),
('At Kamala Hotel', 'Kamala', 'Phuket'),
('Peranakan House', 'Phuket Town', 'Phuket'),
('Lotus Hotel Patong', 'Patong', 'Phuket'),
('Patong Sino House', 'Patong', 'Phuket'),
('BLU PINE Villa & Pool Access', 'Karon', 'Phuket'),
('Sun Hill Hotel Patong', 'Patong', 'Phuket'),
('Gemma Patong', 'Patong', 'Phuket'),
('Best Western Phuket Ocean Resort', 'Karon', 'Phuket'),
('Beehive Boutique Hotel Phuket', 'Phuket Town', 'Phuket'),
('Guesthouse Belvedere', 'Patong', 'Phuket'),
('Summer Breeze Hotel', 'Patong', 'Phuket'),
('Patong Moon Inn Guesthouse', 'Patong', 'Phuket'),
('Bora Bora Villa Phuket', 'Chalong', 'Phuket'),
('The Front Village', 'Karon', 'Phuket'),
('Paradise Inn', 'Phuket', 'Phuket'),
('Royal Beach Residence', 'Patong', 'Phuket'),
('Andaman Seaside Resort', 'Bang Tao', 'Phuket'),
('Hivetel', 'Chalong', 'Phuket'),
('Shanti Lodge Phuket', 'Chalong', 'Phuket'),
('Andaman Seaview Hotel', 'Karon', 'Phuket'),
('ANGPAO HOTEL', 'Ratsada', 'Phuket'),
('Maikhao Hotel', 'Mai Khao', 'Phuket'),
('Saiyuan Residence Phuket', 'Rawai', 'Phuket'),
('Kamala Dreams', 'Kamala', 'Phuket'),
('Minimal House Patong - Adults Only', 'Patong', 'Phuket'),
('Sky Wave Patong', 'Patong', 'Phuket'),
('Wyndham Royal Lee Phuket', 'Sakhu', 'Phuket'),
('iCheck Inn Chill Patong', 'Patong', 'Phuket'),
('Seaview Patong Hotel', 'Patong', 'Phuket'),
('FunDee Boutique Hotel', 'Patong', 'Phuket'),
('Allamanda Laguna Phuket by RESAVA', 'Choeng Thale', 'Phuket'),
('Kalim Resort', 'Patong', 'Phuket'),
('The AIM Patong Hotel', 'Patong', 'Phuket'),
('Chill House @ Nai Yang Beach', 'Nai Yang', 'Phuket'),
('De coze'' Hotel', 'Patong', 'Phuket'),
('Chivatara Resort & Spa Bang Tao Beach', 'Bang Tao', 'Phuket'),
('Malabar Pool Villa Phuket', 'Ratsada', 'Phuket'),
('Micky Monkey Beach Hotel Phuket Maikhao Thailand', 'Mai Khao', 'Phuket'),
('Kamala Cool', 'Kamala', 'Phuket'),
('Memory Karon Resort', 'Karon', 'Phuket'),
('Coconut Village Resort', 'Patong', 'Phuket'),
('Maikhao Beach Residence', 'Mai Khao', 'Phuket'),
('CA Hotel and Residence Phuket', 'Phuket Town', 'Phuket'),
('Racha Island Resort', 'Rawai', 'Phuket'),
('Hip Hostel', 'Patong', 'Phuket'),
('Naka Resort', 'Kamala', 'Phuket'),
('Roost Glamping', 'Rawai', 'Phuket'),
('The Palmery Resort', 'Karon', 'Phuket'),
('Signature Phuket Resort', 'Chalong', 'Phuket'),
('B & B Patong Beach House', 'Patong', 'Phuket'),
('Recenta Suite Phuket Suanluang', 'Phuket Town', 'Phuket'),
('Breezotel', 'Patong', 'Phuket'),
('The Simple Koh Yao Noi', 'Phuket', 'Phuket'),
('OYO 118 Beach Walk Stay', 'Phuket', 'Phuket'),
('Nu Phuket Airport Residence', 'Mai Khao', 'Phuket'),
('Winrisa Place', 'Sakhu', 'Phuket'),
('Naiyang Beach Hotel', 'Nai Yang', 'Phuket'),
('Sugar Marina Hotel - NAUTICAL - Kata Beach', 'Kata', 'Phuket'),
('Moonlight Cottage Phuket', 'Pa Klok', 'Phuket'),
('Garden Home Kata', 'Kata', 'Phuket'),
('Mala Hotel', 'Karon', 'Phuket'),
('Absolute Bangla Suites', 'Patong', 'Phuket'),
('Kata Garden Resort', 'Kata', 'Phuket'),
('Club Bamboo Boutique Patong Beach Resort', 'Patong', 'Phuket'),
('Amarin Hotel Patong', 'Patong', 'Phuket'),
('Seven Seas Hotel', 'Patong', 'Phuket'),
('Baan Boa Resort', 'Patong', 'Phuket'),
('PK Mansion', 'Phuket Town', 'Phuket'),
('Himaphan Boutique Resort', 'Nai Yang', 'Phuket'),
('Coco Paradiso Phuket Hotel', 'Chalong', 'Phuket'),
('Neon Patong Hotel', 'Patong', 'Phuket'),
('Forty Winks Phuket', 'Patong', 'Phuket'),
('Golden Paradise Hotel', 'Karon', 'Phuket'),
('Porterhouse Beach Hotel', 'Patong', 'Phuket'),
('The Front Hotel and Apartment', 'Patong', 'Phuket'),
('The Beach Boutique House', 'Kata', 'Phuket'),
('Loftpical Resort', 'Phuket', 'Phuket'),
('Karon Beach Pool Hotel', 'Karon', 'Phuket'),
('Oceanstone by RESAVA', 'Choeng Thale', 'Phuket'),
('Anattaya Holiday Home', 'Phuket', 'Phuket'),
('Phuket Nonnita Boutique Resort', 'Phuket Town', 'Phuket'),
('Good Nice Hotel Patong', 'Patong', 'Phuket'),
('Villoft Zen Living', 'Choeng Thale', 'Phuket'),
('The Nice Patong Hotel', 'Patong', 'Phuket'),
('Mai Morn Resort', 'Phuket Town', 'Phuket'),
('The Artist House', 'Patong', 'Phuket'),
('Diamond Cottage Resort & Spa', 'Karon', 'Phuket'),
('Ruen Buathong Boutique Hotel', 'Patong', 'Phuket'),
('Park 38 Hotel', 'Phuket Town', 'Phuket'),
('The Pe La Resort, Phuket', 'Kamala', 'Phuket'),
('AJ Residence', 'Ratsada', 'Phuket'),
('Smile Residence', 'Rawai', 'Phuket'),
('P.S2 Resort', 'Patong', 'Phuket'),
('Nankanok Bungalow', 'Phuket', 'Phuket'),
('Kantary Bay Hotel, Phuket', 'Phuket Town', 'Phuket'),
('NOBLE HOUSE PATONG', 'Patong', 'Phuket'),
('Baan Laimai Beach Resort & Spa', 'Patong', 'Phuket'),
('The Guest House - SHA', 'Phuket', 'Phuket'),
('Aquarius Gay Guesthouse & Sauna', 'Patong', 'Phuket'),
('Sleepy Station - Hostel', 'Karon', 'Phuket'),
('Sai Rougn Residence', 'Patong', 'Phuket'),
('Chabana Resort', 'Choeng Thale', 'Phuket'),
('Little Nyonya Hotel', 'Wichit', 'Phuket'),
('Sugar Marina Hotel – FASHION – Kata Beach', 'Kata', 'Phuket'),
('Dome Resort', 'Kata', 'Phuket'),
('Marina House MUAYTHAI Ta-iad Phuket', 'Chalong', 'Phuket'),
('Lae Lay Suites', 'Karon', 'Phuket'),
('Nipa Resort', 'Patong', 'Phuket'),
('Ban Raya Resort and Spa', 'Rawai', 'Phuket'),
('Wanna Marine', 'Patong', 'Phuket'),
('Wyndham La Vita Rawai Phuket', 'Rawai', 'Phuket'),
('Impiana Private Villas Kata Noi', 'Kata', 'Phuket'),
('Sivana Place Phuket', 'Choeng Thale', 'Phuket'),
('Naiyang Place Phuket Airport', 'Nai Yang', 'Phuket'),
('Palm Garden Resort', 'Rawai', 'Phuket'),
('Casa Jip Guesthouse', 'Patong', 'Phuket'),
('Z&Z Resort', 'Rawai', 'Phuket'),
('The Kiri Villas Resort', 'Si Sunthon', 'Phuket'),
('Leelawadee Naka', 'Phuket Town', 'Phuket'),
('Karon Café Inn', 'Karon', 'Phuket'),
('Pamookkoo Resort', 'Kata', 'Phuket'),
('Starbeach Guest House', 'Patong', 'Phuket'),
('New Forest Patong', 'Patong', 'Phuket'),
('Sunrise Beach Koh Yao Resort', 'Phuket', 'Phuket'),
('The Mangrove Panwa Phuket Resort', 'Phuket Town', 'Phuket'),
('Naka Residence', 'Phuket Town', 'Phuket'),
('Grand Sunset Hotel Phuket', 'Karon', 'Phuket'),
('Kana Triple L Hotel', 'Patong', 'Phuket'),
('Tinidee Golf Resort Phuket', 'Kathu', 'Phuket'),
('ASHLEE Heights Hotel Patong', 'Patong', 'Phuket'),
('The Palms Kamala Beach', 'Kamala', 'Phuket'),
('Mom Tri''s Villa Royale', 'Kata', 'Phuket'),
('Chalong Chalet Resort & Longstay', 'Chalong', 'Phuket'),
('Ramaburin Resort', 'Patong', 'Phuket'),
('Citrus Patong Hotel by Compass Hospitality', 'Patong', 'Phuket'),
('The Expat Hotel', 'Patong', 'Phuket'),
('Coco Retreat Phuket Resort & Spa', 'Chalong', 'Phuket'),
('Capricorn Village', 'Patong', 'Phuket'),
('Kata Hill Sea View', 'Kata', 'Phuket'),
('The View Rawada Phuket', 'Phuket', 'Phuket'),
('The Lake Chalong Hotel', 'Chalong', 'Phuket'),
('Hotel Sole', 'Patong', 'Phuket'),
('Karon Village Hotel', 'Karon', 'Phuket'),
('The Regent Phuket Bangtao Beach', 'Bang Tao', 'Phuket'),
('Twinpalms MontAzure Phuket Resort', 'Kamala', 'Phuket'),
('Amber Residence', 'Phuket', 'Phuket'),
('Phuket Boat Quay', 'Phuket', 'Phuket'),
('The Album Hotel', 'Patong', 'Phuket'),
('A2 Pool Resort', 'Phuket Town', 'Phuket'),
('Baan Yin Dee Boutique Resort', 'Patong', 'Phuket'),
('beHOME Phuket', 'Nai Yang', 'Phuket'),
('Patong Mansion Hotel', 'Patong', 'Phuket'),
('Patong Palace Hotel', 'Patong', 'Phuket'),
('The Racha', 'Rawai', 'Phuket'),
('The Viridian Resort', 'Patong', 'Phuket'),
('Quality Beach Resorts and Spa Patong', 'Patong', 'Phuket'),
('The Woods Natural Park Resort Phuket', 'Kamala', 'Phuket'),
('Nonnee', 'Kata', 'Phuket'),
('Casa Del M Phuket', 'Patong', 'Phuket'),
('ASHLEE Hub Hotel Patong', 'Patong', 'Phuket'),
('The Blue Pearl Kata Hotel', 'Kata', 'Phuket'),
('Koyao Island Resort', 'Phuket', 'Phuket'),
('Bangtao Village Resort', 'Bang Tao', 'Phuket'),
('Artisan Koh Yao Yai', 'Phuket', 'Phuket'),
('JB Green Hotel Patong', 'Patong', 'Phuket'),
('The Mooring Resort', 'Wichit', 'Phuket'),
('Kokotel Phuket Patong', 'Patong', 'Phuket'),
('7Q Patong Beach Hotel', 'Patong', 'Phuket'),
('The Album Loft at Nanai', 'Kathu', 'Phuket'),
('The Beach Heights Resort', 'Kata', 'Phuket'),
('Kamala Beach Estate', 'Kamala', 'Phuket'),
('Kamala Beachfront Apartment', 'Kamala', 'Phuket'),
('Nicky''s Handlebar Hotel', 'Patong', 'Phuket'),
('Sugar Marina Resort -Surf- Kata Beach', 'Kata', 'Phuket'),
('Pimnara Boutique Hotel', 'Patong', 'Phuket'),
('Hotel The Journey Patong New', 'Patong', 'Phuket'),
('The House Patong', 'Patong', 'Phuket'),
('The Sixteenth Naiyang Beach Hotel', 'Nai Yang', 'Phuket'),
('The Loft Panwa Resort', 'Phuket Town', 'Phuket'),
('Sai Kaew House', 'Thalang', 'Phuket'),
('Phaithong Sotel Resort', 'Chalong', 'Phuket'),
('The Yorkshire Hotel', 'Patong', 'Phuket'),
('Rak Elegant Hotel Patong', 'Patong', 'Phuket'),
('Clarian Hotel Beach Patong', 'Patong', 'Phuket'),
('Chalong Miracle Lakeview Resort & Spa', 'Chalong', 'Phuket'),
('Phuketa Hotel', 'Phuket Town', 'Phuket'),
('My Hotel', 'Phuket', 'Phuket'),
('Thanyapura Sports & Health Resort', 'Thep Krasattri', 'Phuket'),
('ACCESS Resort & Villas', 'Karon', 'Phuket'),
('Airport Beach Hotel Phuket', 'Sakhu', 'Phuket'),
('Princess Seaview Resort & Spa', 'Phuket Town', 'Phuket'),
('Armoni Patong Beach Hotel', 'Patong', 'Phuket'),
('Andaman Beach Suites Hotel', 'Patong', 'Phuket'),
('Bel Aire Resort Phuket', 'Patong', 'Phuket'),
('ibis Phuket Patong', 'Patong', 'Phuket'),
('Marina Gallery Resort Kacha Kalim Bay', 'Patong', 'Phuket'),
('Homm Bliss Southbeach Patong', 'Patong', 'Phuket'),
('Nize Hotel', 'Phuket', 'Phuket'),
('The Patong Center Hotel', 'Patong', 'Phuket'),
('Wabi Sabi Boutique Hotel', 'Kamala', 'Phuket'),
('Centro One Patong', 'Patong', 'Phuket'),
('Naiya Beach Bungalow', 'Phuket', 'Phuket'),
('The Little Mermaid Guesthouse & Restaurant', 'Karon', 'Phuket'),
('At Night Airport Resort', 'Phuket', 'Phuket'),
('Lamai Hotel', 'Patong', 'Phuket'),
('Little Loft Hotel', 'Wichit', 'Phuket'),
('Chalong Sea Breeze', 'Rawai', 'Phuket'),
('Horizon Karon Beach Resort & Spa', 'Karon', 'Phuket'),
('Ban Paea', 'Phuket', 'Phuket'),
('Baan Kamala Fantasea Hotel', 'Kamala', 'Phuket'),
('Areca Resort & Spa', 'Phuket Town', 'Phuket'),
('Koh Yao Yai Hillside Resort', 'Phuket', 'Phuket'),
('Baan Thai Beach Side Residence', 'Patong', 'Phuket'),
('The Lantern Resorts Patong', 'Patong', 'Phuket'),
('Baipho Lifestyle', 'Kathu', 'Phuket'),
('Purana Resort Koh Yao Noi', 'Phuket', 'Phuket'),
('Patong Dynasty Royal Hotel', 'Patong', 'Phuket'),
('Paradise KohYao', 'Phuket', 'Phuket'),
('Peach Blossom Resort', 'Karon', 'Phuket'),
('Naiyang Park Resort', 'Nai Yang', 'Phuket'),
('Orchid Garden Hotel', 'Kathu', 'Phuket'),
('Kata Poolside Resort', 'Kata', 'Phuket'),
('ASHLEE Plaza Patong Hotel & Spa', 'Patong', 'Phuket'),
('Anda Beachside Hotel', 'Karon', 'Phuket'),
('Beyond Patong', 'Patong', 'Phuket'),
('Thanthip Beach Resort', 'Patong', 'Phuket'),
('Centre Point Patong', 'Patong', 'Phuket'),
('O''nya Phuket Hotel', 'Phuket Town', 'Phuket'),
('Phuvaree Resort', 'Patong', 'Phuket'),
('foto Hotel Phuket', 'Ratsada', 'Phuket'),
('The Color Kata', 'Kata', 'Phuket'),
('Karon Phunaka Resort', 'Karon', 'Phuket'),
('Patong Lodge Hotel', 'Patong', 'Phuket'),
('Phuket Island View Resort', 'Karon', 'Phuket'),
('Paripas Express Hotel Patong', 'Patong', 'Phuket'),
('The Frutta Boutique Patong Beach', 'Patong', 'Phuket'),
('Sea Front Home', 'Patong', 'Phuket'),
('Boomerang Inn', 'Phuket', 'Phuket'),
('SR Sea View Apartments', 'Patong', 'Phuket'),
('The Thames Pool Access Resort SHA+', 'Chalong', 'Phuket'),
('GLOW Mira Karon Beach', 'Karon', 'Phuket'),
('Alfresco Phuket Hotel', 'Kathu', 'Phuket'),
('Red Planet Phuket Patong', 'Patong', 'Phuket'),
('Aqua Resort', 'Rawai', 'Phuket'),
('V Villas Phuket - MGallery', 'Phuket Town', 'Phuket'),
('Peach Hill Resort', 'Karon', 'Phuket'),
('Patong Hemingway''s Hotel', 'Patong', 'Phuket'),
('Sino Maison Hotel', 'Patong', 'Phuket'),
('By the Sea', 'Wichit', 'Phuket'),
('Maikhao Dream Villa Resort & Spa', 'Mai Khao', 'Phuket'),
('Sugar Marina Hotel - ART - Karon Beach', 'Karon', 'Phuket'),
('Kamala Phuyai Resort', 'Patong', 'Phuket'),
('Beyond Karon', 'Karon', 'Phuket'),
('Naina Resort & Spa', 'Patong', 'Phuket'),
('Banhalawee', 'Phuket', 'Phuket'),
('Phuket Sea Resort', 'Rawai', 'Phuket'),
('R Mar Resort and Spa', 'Patong', 'Phuket'),
('The Luna Hostel', 'Nai Yang', 'Phuket'),
('DARA Hotel', 'Phuket Town', 'Phuket'),
('Coco Boutique Hotel', 'Patong', 'Phuket'),
('Wekata Luxury', 'Kata', 'Phuket'),
('Kudo Hotel & Beach Club (Adults Only)', 'Patong', 'Phuket'),
('The Boathouse Phuket', 'Kata', 'Phuket'),
('The Bell Airport Phuket Hotel', 'Nai Yang', 'Phuket'),
('Perennial Resort', 'Phuket', 'Phuket'),
('BYD Lofts Boutique Hotel & Serviced Apartments - Patong Beach, Phuket', 'Patong', 'Phuket'),
('Baumancasa Beach Resort', 'Karon', 'Phuket'),
('CRAFT Resort & Villas', 'Phuket Town', 'Phuket'),
('Mövenpick Phuket Bangtao', 'Bang Tao', 'Phuket'),
('On The Hill Karon Resort', 'Karon', 'Phuket'),
('Coriacea Boutique Resort', 'Mai Khao', 'Phuket'),
('Paresa Resort Phuket', 'Kamala', 'Phuket'),
('Absolute Twin Sands Resort & Spa', 'Patong', 'Phuket'),
('Kata White Villas', 'Kata', 'Phuket'),
('New Square Patong Hotel', 'Patong', 'Phuket'),
('La Vista Patong Hotel', 'Patong', 'Phuket'),
('The Village Resort & Spa', 'Karon', 'Phuket'),
('Trisara Villas & Residences Phuket', 'Choeng Thale', 'Phuket'),
('Cape Kudu Hotel', 'Phuket', 'Phuket'),
('Woraburi Phuket Resort & Spa', 'Karon', 'Phuket'),
('Ratana Apart Hotel at Chalong', 'Chalong', 'Phuket'),
('JonoX Phuket Karon Hotel', 'Karon', 'Phuket'),
('Phuket Orchid Resort and Spa', 'Karon', 'Phuket'),
('BearPacker Patong Hostel', 'Patong', 'Phuket'),
('Ratana Hotel Rassada', 'Phuket Town', 'Phuket'),
('myPatong Social Hostel', 'Patong', 'Phuket'),
('Elixir Koh Yao Yai', 'Phuket', 'Phuket'),
('Secret Cliff Resort Phuket', 'Karon', 'Phuket'),
('Beyond Kata', 'Kata', 'Phuket'),
('Nai Yang Beach Resort & Spa', 'Nai Yang', 'Phuket'),
('Royal Yao Yai Island Beach Resort -sha Extra Plus+', 'Phuket', 'Phuket'),
('77 Patong Hotel & Spa', 'Patong', 'Phuket'),
('Six Senses Yao Noi', 'Phuket', 'Phuket'),
('TreeHouse Villas - Adults Only', 'Phuket', 'Phuket'),
('Cape Panwa Hotel', 'Phuket Town', 'Phuket'),
('SALA Phuket Mai Khao Beach Resort', 'Mai Khao', 'Phuket'),
('Karon Sea Sands Resort', 'Karon', 'Phuket'),
('Navatara Phuket Resort', 'Rawai', 'Phuket'),
('Karona Resort & Spa', 'Karon', 'Phuket'),
('Naiharn Beach Resort', 'Rawai', 'Phuket'),
('Baan Karon Hill Phuket Resort', 'Karon', 'Phuket'),
('Ramada by Wyndham Phuket Deevana Patong', 'Patong', 'Phuket'),
('Icheck Inn Darisa Patong', 'Patong', 'Phuket'),
('The Little Moon Residence', 'Patong', 'Phuket'),
('B2 Phuket Premier Hotel', 'Kathu', 'Phuket'),
('Kata Rocks', 'Kata', 'Phuket'),
('Tour De Phuket Hotel', 'Si Sunthon', 'Phuket'),
('Ma Doo Bua Phuket (มาดูบัวภูเก็ต)', 'Choeng Thale', 'Phuket'),
('Benjamin Resort', 'Kathu', 'Phuket'),
('The Old Phuket - Karon Beach Resort', 'Karon', 'Phuket'),
('Wyndham Grand Nai Harn Beach Phuket', 'Rawai', 'Phuket'),
('The Crystal Beach Hotel', 'Patong', 'Phuket'),
('Centro One Bangla', 'Patong', 'Phuket'),
('Slumber Party Surf Kata Phuket', 'Kata', 'Phuket'),
('Royal Phawadee Village', 'Patong', 'Phuket'),
('SKYVIEW Resort Phuket Patong Beach', 'Patong', 'Phuket'),
('Honey Resort', 'Kata', 'Phuket'),
('Maya Phuket Airport Hotel', 'Nai Yang', 'Phuket'),
('Tuana Hotels Casa Del Sol', 'Karon', 'Phuket'),
('Island Patong Beachfront Apartments', 'Patong', 'Phuket'),
('Thiw Son Beach Resort', 'Phuket', 'Phuket'),
('Suuko Wellness & Spa Resort', 'Chalong', 'Phuket'),
('Freedom', 'Kathu', 'Phuket'),
('Phuket Airport Place', 'Mai Khao', 'Phuket'),
('Seabed Grand Hotel Phuket', 'Wichit', 'Phuket'),
('CC''s Hideaway', 'Karon', 'Phuket'),
('Baumanburi', 'Patong', 'Phuket'),
('Limburi Hometel', 'Patong', 'Phuket'),
('Layalina Hotel', 'Kamala', 'Phuket'),
('Andaman White Beach Resort', 'Thalang', 'Phuket'),
('Bt Inn Patong', 'Patong', 'Phuket'),
('Phuket Airport Sonwa Resort', 'Sakhu', 'Phuket'),
('TJ Patong Hotel', 'Patong', 'Phuket'),
('Chanalai Hillside Resort, Karon Beach', 'Karon', 'Phuket'),
('Chabana Kamala Hotel', 'Patong', 'Phuket'),
('Aurico Kata Resort & Spa', 'Kata', 'Phuket'),
('Andaman Beach Hotel Phuket - Handwritten Collection', 'Patong', 'Phuket'),
('The Beachfront Hotel Phuket', 'Rawai', 'Phuket'),
('Phunawa Resort', 'Phuket Town', 'Phuket'),
('Sleep Inn Phuket', 'Patong', 'Phuket'),
('Best Western Patong Beach', 'Patong', 'Phuket'),
('Andaman Cannacia Resort & Spa', 'Kata', 'Phuket'),
('Orchidacea Resort', 'Karon', 'Phuket'),
('Airport Resort Phuket', 'Sakhu', 'Phuket'),
('Tanawan Phuket Hotel', 'Patong', 'Phuket'),
('Kata Sea Breeze Resort', 'Kata', 'Phuket'),
('S4 Nai Yang Beach', 'Nai Yang', 'Phuket'),
('Naithonburi Beach Resort', 'Sakhu', 'Phuket'),
('Woovo Phuket Patong', 'Patong', 'Phuket'),
('Sunray Beach Hotel', 'Patong', 'Phuket'),
('Centara Karon Resort Phuket', 'Karon', 'Phuket'),
('Ocean View Treasure Residence', 'Patong', 'Phuket'),
('Mövenpick Myth Hotel Patong Phuket', 'Patong', 'Phuket'),
('Phuket Airport Hotel', 'Phuket', 'Phuket'),
('MAZI Design Hotel by Kalima', 'Patong', 'Phuket'),
('Amora Beach Resort Phuket', 'Bang Tao', 'Phuket'),
('NH Boat Lagoon Phuket Resort', 'Phuket Town', 'Phuket'),
('Sea Pearl Beach Resort', 'Patong', 'Phuket'),
('Metadee Concept Hotel', 'Kata', 'Phuket'),
('SLEEP WITH ME HOTEL design hotel @ patong', 'Patong', 'Phuket'),
('David Residence', 'Mai Khao', 'Phuket'),
('Aspery Hotel', 'Patong', 'Phuket'),
('The Bloc Hotel', 'Patong', 'Phuket'),
('Thavorn Palm Beach Resort Phuket', 'Karon', 'Phuket'),
('Avani+ Mai Khao Phuket Suites', 'Mai Khao', 'Phuket'),
('Princess Kamala Beachfront Hotel', 'Kamala', 'Phuket'),
('Sunsuri Phuket', 'Phuket Town', 'Phuket'),
('Cassia Phuket - a brand of Banyan Group', 'Choeng Thale', 'Phuket'),
('OZO Phuket', 'Kata', 'Phuket'),
('The Kee Resort & Spa', 'Patong', 'Phuket'),
('Novotel Phuket Kamala Beach', 'Kamala', 'Phuket'),
('The Crib Patong', 'Patong', 'Phuket'),
('The Senses Resort & Pool Villas, Phuket', 'Patong', 'Phuket'),
('APK Resort', 'Patong', 'Phuket'),
('Dusit Thani Laguna Phuket', 'Choeng Thale', 'Phuket'),
('Acca Patong Apartments', 'Patong', 'Phuket'),
('Patong Bay Residence', 'Patong', 'Phuket'),
('Melia Phuket Mai Khao', 'Mai Khao', 'Phuket'),
('Rosewood Phuket', 'Patong', 'Phuket'),
('The Naka Island, a Luxury Collection Resort & Spa, Phuket', 'Pa Klok', 'Phuket'),
('Keemala', 'Kamala', 'Phuket'),
('Andakira Hotel', 'Patong', 'Phuket'),
('Silver Resortel', 'Patong', 'Phuket'),
('Baan Yuree Resort and Spa', 'Patong', 'Phuket'),
('Renaissance Phuket Resort & Spa', 'Mai Khao', 'Phuket'),
('Noku Phuket', 'Chalong', 'Phuket'),
('Barcelo Coconut Island Phuket', 'Phuket Town', 'Phuket'),
('Chanalai Flora Resort, Kata Beach', 'Kata', 'Phuket'),
('The Surin Phuket', 'Surin', 'Phuket'),
('Orchid Resortel', 'Patong', 'Phuket'),
('The Gig Hotel', 'Patong', 'Phuket'),
('IndoChine Resort & Villas', 'Patong', 'Phuket'),
('Kata Palm Resort', 'Kata', 'Phuket'),
('Buasri Boutique Patong', 'Patong', 'Phuket'),
('Radisson Resort and Suites Phuket', 'Kamala', 'Phuket'),
('Aochalong Villa Resort & Spa', 'Chalong', 'Phuket'),
('Baan Karonburi Resort', 'Karon', 'Phuket'),
('Patong Poshtel - Adults Only - Hostel', 'Patong', 'Phuket'),
('PJ Patong Resortel', 'Patong', 'Phuket'),
('Friendship Beach Resort & Atmanjai Wellness Spa', 'Rawai', 'Phuket'),
('Nouveau Guesthouse', 'Kathu', 'Phuket'),
('P R Patong Hotel', 'Patong', 'Phuket'),
('Sugar Marina Hotel - AVIATOR - Phuket Airport', 'Sakhu', 'Phuket'),
('Bauman residence Patong, Phuket', 'Patong', 'Phuket'),
('The Lunar Patong', 'Patong', 'Phuket'),
('Baba House Phuket Hotel', 'Wichit', 'Phuket'),
('Tropica Bungalow Resort', 'Patong', 'Phuket'),
('Zenmaya Oceanfront Phuket, Trademark Collection by Wyndham', 'Phuket', 'Phuket'),
('Sunwing Kamala Beach', 'Kamala', 'Phuket'),
('Twinpalms Surin Phuket Resort', 'Surin', 'Phuket'),
('Phuket Airport Inn', 'Sakhu', 'Phuket'),
('Rawai Palm Beach Resort', 'Rawai', 'Phuket'),
('Proud Phuket', 'Nai Yang', 'Phuket'),
('Bandara Villas Phuket', 'Phuket Town', 'Phuket'),
('OUTRIGGER Surin Beach Resort', 'Surin', 'Phuket'),
('The SIS Kata Resort - Adult Only', 'Kata', 'Phuket'),
('Fusion Suites Phuket Patong', 'Patong', 'Phuket'),
('The Yama Hotel Phuket', 'Karon', 'Phuket'),
('Koh Yao Yai Village', 'Phuket', 'Phuket'),
('Impiana Resort Patong', 'Patong', 'Phuket'),
('Andamantra Resort and Villa Phuket', 'Patong', 'Phuket'),
('Andaman Embrace Patong', 'Patong', 'Phuket'),
('Selina Serenity Rawai Phuket', 'Rawai', 'Phuket'),
('Bauman Ville Hotel', 'Patong', 'Phuket'),
('LIV Hotel Phuket Patong Beachfront', 'Patong', 'Phuket'),
('Maikhao Palm Beach Resort', 'Mai Khao', 'Phuket'),
('Patong Paragon Resort & Spa', 'Patong', 'Phuket'),
('Arinara Beach Resort Phuket', 'Bang Tao', 'Phuket'),
('Chanalai Romantica Resort Kata Beach - Adults Only', 'Kata', 'Phuket'),
('The Pago Design Hotel Phuket', 'Phuket Town', 'Phuket'),
('THE NATURAL RESORT', 'Patong', 'Phuket'),
('MIDA Grande Resort Phuket', 'Surin', 'Phuket'),
('Tony Resort', 'Patong', 'Phuket'),
('La Flora Resort Patong', 'Patong', 'Phuket'),
('Patong Heritage', 'Patong', 'Phuket'),
('Sinae Phuket', 'Phuket Town', 'Phuket'),
('Angsana Laguna Phuket', 'Choeng Thale', 'Phuket'),
('C & N Hotel Patong', 'Patong', 'Phuket'),
('Kata Beachwalk Hotel and Bungalows', 'Kata', 'Phuket'),
('Deevana Plaza Phuket', 'Patong', 'Phuket'),
('Journeyhub Phuket Patong', 'Patong', 'Phuket'),
('Phuket Siray Hut Resort', 'Rawai', 'Phuket'),
('Fishermen''s Harbour Urban Resort', 'Patong', 'Phuket'),
('Le Meridien Phuket Beach Resort', 'Karon', 'Phuket'),
('Zenseana Resort & Spa', 'Patong', 'Phuket'),
('Le Resort and Villas', 'Kata', 'Phuket'),
('Katathani Phuket Beach Resort', 'Kata', 'Phuket'),
('Phuket Marriott Resort and Spa, Nai Yang Beach', 'Nai Yang', 'Phuket'),
('JW Marriott Phuket Resort & Spa', 'Mai Khao', 'Phuket'),
('COMO Point Yamu, Phuket', 'Pa Klok', 'Phuket'),
('Nap Patong', 'Patong', 'Phuket'),
('Pullman Phuket Karon Beach Resort', 'Karon', 'Phuket'),
('Hotel Indigo Phuket Patong, an IHG Hotel', 'Patong', 'Phuket'),
('Pullman Phuket Arcadia Naithon Beach', 'Phuket', 'Phuket'),
('Wyndham Sea Pearl Resort Phuket', 'Patong', 'Phuket'),
('The Nature Phuket', 'Patong', 'Phuket'),
('Panwaburi Beachfront Resort', 'Phuket Town', 'Phuket'),
('Hotel Baya Patong', 'Patong', 'Phuket'),
('Patong Resort', 'Patong', 'Phuket'),
('Seeka Boutique Resort', 'Patong', 'Phuket'),
('Splash Beach Resort, Mai Khao, Phuket', 'Mai Khao', 'Phuket'),
('SAii Laguna Phuket', 'Bang Tao', 'Phuket'),
('Grand Mercure Phuket Patong', 'Patong', 'Phuket'),
('The Charm Resort Phuket', 'Patong', 'Phuket'),
('Kamala Beach Resort, A Sunprime Resort - Adults Only', 'Kamala', 'Phuket'),
('Courtyard by Marriott Phuket, Patong Beach Resort', 'Patong', 'Phuket'),
('Novotel Phuket Resort', 'Patong', 'Phuket'),
('The Marina Phuket Hotel', 'Patong', 'Phuket'),
('Avista Hideaway Phuket Patong - MGallery', 'Patong', 'Phuket'),
('Oceanfront Beach Resort', 'Patong', 'Phuket'),
('Holiday Inn Resort Phuket, an IHG Hotel', 'Patong', 'Phuket'),
('Holiday Inn Express Phuket Patong Beach Central, an IHG Hotel', 'Patong', 'Phuket'),
('Centara Grand Beach Resort Phuket', 'Karon', 'Phuket'),
('Pacific Club Resort', 'Phuket', 'Phuket'),
('Amatara Welleisure Resort', 'Phuket', 'Phuket'),
('Dinso Resort & Villas Phuket, Vignette Collection, an IHG Hotel', 'Patong', 'Phuket'),
('Phuket Panwa Beachfront Resort', 'Phuket Town', 'Phuket'),
('M Social Hotel Phuket', 'Patong', 'Phuket'),
('Palmyra Patong Resort', 'Patong', 'Phuket'),
('Amata Patong', 'Patong', 'Phuket'),
('The Royal Paradise Hotel & Spa', 'Patong', 'Phuket'),
('Dewa Phuket Resort & Villas', 'Thalang', 'Phuket'),
('The Shore at Katathani', 'Kata', 'Phuket'),
('Holiday Inn Resort Phuket Surin Beach, an IHG Hotel', 'Surin', 'Phuket'),
('Burasari Phuket Resort & Spa', 'Patong', 'Phuket'),
('Stay Wellbeing & Lifestyle Resort', 'Rawai', 'Phuket'),
('Crest Resort & Pool Villas', 'Patong', 'Phuket'),
('Le Méridien Phuket Mai Khao Beach Resort', 'Mai Khao', 'Phuket'),
('Hallo Patong Hotel & Restaurant', 'Patong', 'Phuket'),
('Wyndham Grand Phuket Kalim Bay', 'Kamala', 'Phuket'),
('Hotel IKON Phuket', 'Karon', 'Phuket'),
('Hyatt Regency Phuket Resort', 'Kamala', 'Phuket'),
('The Vijitt Resort Phuket', 'Rawai', 'Phuket'),
('L''esprit de Naiyang Beach Resort', 'Nai Yang', 'Phuket'),
('Novotel Phuket Kata Avista Resort And Spa', 'Kata', 'Phuket'),
('Kalima Resort & Spa, Phuket', 'Patong', 'Phuket'),
('InterContinental Phuket Resort, an IHG Hotel', 'Kamala', 'Phuket'),
('Chanalai Garden Resort, Kata Beach', 'Kata', 'Phuket'),
('Lub d Phuket Patong - Hostel', 'Patong', 'Phuket'),
('Thavorn Beach Village Resort & Spa Phuket', 'Kamala', 'Phuket'),
('Cape Sienna Gourmet Hotel & Villas', 'Kamala', 'Phuket'),
('DoubleTree by Hilton Phuket Banthai Resort', 'Patong', 'Phuket'),
('Novotel Phuket Vintage Park', 'Patong', 'Phuket'),
('Duangjitt Resort, Phuket', 'Patong', 'Phuket'),
('The Pavilions Phuket', 'Choeng Thale', 'Phuket'),
('Panphuree Residence', 'Sakhu', 'Phuket'),
('Centara Kata Resort Phuket', 'Kata', 'Phuket'),
('Modern Living Hotel', 'Patong', 'Phuket'),
('Ramada Plaza by Wyndham Chao Fah', 'Wichit', 'Phuket'),
('Destination Patong', 'Patong', 'Phuket'),
('Paripas Patong Resort', 'Patong', 'Phuket'),
('Sawasdee Village', 'Kata', 'Phuket'),
('Centara Villas Phuket', 'Karon', 'Phuket'),
('The Slate', 'Sakhu', 'Phuket'),
('My Beach Resort Phuket', 'Phuket Town', 'Phuket'),
('Bandara Phuket Beach Resort', 'Phuket Town', 'Phuket'),
('Deevana Patong Resort & Spa', 'Patong', 'Phuket'),
('The Chilli by Golden Ray', 'Kathu', 'Phuket'),
('The Nai Harn', 'Rawai', 'Phuket'),
('Sawaddi Patong Resort & Spa by Tolani', 'Patong', 'Phuket'),
('Sunwing Bangtao Beach', 'Bang Tao', 'Phuket'),
('Anantara Layan Phuket Resort', 'Choeng Thale', 'Phuket'),
('Star Guesthouse', 'Patong', 'Phuket'),
('The BluEco Hotel', 'Karon', 'Phuket'),
('Pullman Phuket Panwa Beach Resort', 'Wichit', 'Phuket'),
('Avista Grande Phuket Karon - MGallery', 'Karon', 'Phuket'),
('Villa Zolitude Resort & Spa', 'Chalong', 'Phuket'),
('Hilton Garden Inn Phuket, Thailand', 'Choeng Thale', 'Phuket'),
('La Vintage Resort', 'Patong', 'Phuket'),
('Supalai Scenic Bay Resort And Spa', 'Pa Klok', 'Phuket'),
('The Naka Phuket, a member of Design Hotels', 'Kamala', 'Phuket'),
('Grand Kata VIP - Kata Beach', 'Kata', 'Phuket'),
('Sunset Beach Resort', 'Patong', 'Phuket'),
('Patong Bay Hill Resort', 'Patong', 'Phuket'),
('Namaka Resort Kamala', 'Kamala', 'Phuket'),
('Anantara Mai Khao Phuket Villas', 'Mai Khao', 'Phuket'),
('Anantara Koh Yao Yai Resort & Villas', 'Phuket', 'Phuket'),
('Island Escape Burasari', 'Phuket', 'Phuket'),
('At Night Airport Resort', 'Phuket', 'Phuket'),
('Andara Resort Villas', 'Kathu', 'Phuket'),
('Remember @ Phuket Town', 'Phuket Town', 'Phuket'),
('Gotum Hostel 2 at Thalang Road', 'Phuket Town', 'Phuket'),
('Green Leaf Hostel', 'Phuket Town', 'Phuket'),
('Sino Inn', 'Phuket Town', 'Phuket'),
('Le Hua', 'Phuket Town', 'Phuket'),
('bloo Hostel', 'Phuket Town', 'Phuket'),
('PERA Space Capsule Hotel', 'Phuket Town', 'Phuket'),
('Eco Hostel Phuket', 'Phuket Town', 'Phuket'),
('The Royal P Boutique Hotel', 'Phuket Town', 'Phuket'),
('Ritsurin Boutique Hotel', 'Phuket Town', 'Phuket'),
('Sunny Hostel Phuket', 'Phuket Town', 'Phuket'),
('Capzule Bed Phuket', 'Phuket Town', 'Phuket'),
('BAAN125 STAY', 'Phuket Town', 'Phuket'),
('Siri Hotel Phuket', 'Phuket Town', 'Phuket'),
('Baan Sutra Guesthouse', 'Phuket Town', 'Phuket'),
('C.A.P. Mansion Hotel', 'Wichit', 'Phuket'),
('Chaphone Guesthouse', 'Phuket Town', 'Phuket'),
('Nawaporn Place Guesthouse', 'Phuket Town', 'Phuket'),
('Twin Hotel', 'Phuket Town', 'Phuket'),
('Shunli Hostel', 'Phuket Town', 'Phuket'),
('OYO 1172 Goodnight Resort', 'Phuket Town', 'Phuket'),
('Sabaidee Residence', 'Phuket Town', 'Phuket'),
('Beehive Phuket Old Town - Hostel', 'Phuket Town', 'Phuket'),
('Rome Place Hotel', 'Phuket Town', 'Phuket'),
('Ang Mor Lao Poshtel - Adults Only - Hostel', 'Phuket Town', 'Phuket'),
('Studio309@Phuket', 'Phuket Town', 'Phuket'),
('The WIDE Condotel - Phuket', 'Phuket Town', 'Phuket'),
('Sino Imperial Design Hotel', 'Phuket Town', 'Phuket'),
('Baan Baan Hostel', 'Phuket Town', 'Phuket'),
('The Duck', 'Phuket Town', 'Phuket'),
('The Rommanee Boutique Guesthouse', 'Phuket Town', 'Phuket'),
('Ai Phuket Hostel', 'Phuket Town', 'Phuket'),
('Sunrise Phuket Homestay', 'Phuket', 'Phuket'),
('Phuthara Hostel', 'Phuket Town', 'Phuket'),
('The urban room', 'Phuket Town', 'Phuket'),
('Gotum Hostel & Restaurant', 'Phuket Town', 'Phuket'),
('The One Place Prasart', 'Phuket', 'Phuket'),
('Rang Hill Residence', 'Phuket Town', 'Phuket'),
('Little Bird Phuket', 'Phuket Town', 'Phuket'),
('Vitamin Sea Hostel Phuket', 'Phuket', 'Phuket'),
('Art C House', 'Phuket Town', 'Phuket'),
('Feel Good Hostel', 'Phuket Town', 'Phuket'),
('Best Stay Hostel', 'Phuket', 'Phuket'),
('ZEN Rooms Takua Thung Road', 'Phuket', 'Phuket'),
('OYO 501 At Night Hostel', 'Phuket Town', 'Phuket'),
('Ok Chic Phuket Hostel', 'Phuket Town', 'Phuket'),
('White Wall Poshtel - Hostel', 'Phuket Town', 'Phuket'),
('Seabreeze Mansion', 'Phuket Town', 'Phuket'),
('Nine Inn at Town', 'Chalong', 'Phuket'),
('Karnvela Phuket', 'Phuket Town', 'Phuket'),
('OYO 75311 Bed One', 'Phuket Town', 'Phuket'),
('Pakta Phuket', 'Phuket', 'Phuket'),
('Baan Rachapuek', 'Phuket Town', 'Phuket'),
('Ekkamon Mansion', 'Phuket Town', 'Phuket'),
('Go Inn Phuket Old Town', 'Phuket Town', 'Phuket'),
('Bed Hostel', 'Phuket Town', 'Phuket'),
('OYO 778 21 Poshtel', 'Phuket Town', 'Phuket'),
('OYO 1163 Eden Hostel', 'Phuket Town', 'Phuket'),
('Cafe66 Hostel', 'Phuket Town', 'Phuket'),
('OYO 1054 Phuket Backpacker Hostel', 'Phuket Town', 'Phuket'),
('Feelgood@Journey Hostel', 'Phuket Town', 'Phuket'),
('OYO 889 Baan Sakdidet', 'Phuket Town', 'Phuket'),
('Befine Guesthouse', 'Phuket Town', 'Phuket'),
('Phuket Town Inn', 'Phuket Town', 'Phuket'),
('The Urban Room', 'Phuket', 'Phuket'),
('Eden Hostel', 'Phuket Town', 'Phuket'),
('Thalang Guesthouse', 'Phuket Town', 'Phuket'),
('ZEN Rooms Dibuk Phuket Town', 'Phuket Town', 'Phuket'),
('Paradox Resort Phuket', 'Karon', 'Phuket'),
('Amari Phuket', 'Patong', 'Phuket'),
('Four Points by Sheraton Phuket Patong Beach Resort', 'Patong', 'Phuket'),
('Phuket Marriott Resort & Spa, Merlin Beach', 'Patong', 'Phuket'),
('Diamond Cliff Resort & Spa, Patong Beach', 'Patong', 'Phuket'),
('Santhiya Koh Yao Yai Resort & Spa - Compulsory Join Santhiya Speedboat from / to Ao Po Grand Marina at Phuket', 'Phuket', 'Phuket'),
('Mandarava Resort and Spa Karon Beach', 'Karon', 'Phuket'),
('The Westin Siray Bay Resort & Spa, Phuket', 'Phuket Town', 'Phuket'),
('Banyan Tree Phuket', 'Choeng Thale', 'Phuket'),
('Phuket Graceland Resort And Spa', 'Patong', 'Phuket'),
('Hotel Clover Patong Phuket', 'Patong', 'Phuket'),
('Courtyard by Marriott Phuket Town', 'Surin', 'Phuket'),
('Pearl Hotel Phuket', 'Phuket Town', 'Phuket'),
('Vapa Hotel', 'Phuket Town', 'Phuket'),
('Nanachart Mansion', 'Phuket', 'Phuket'),
('Baan Suwantawe', 'Phuket Town', 'Phuket'),
('Novotel Phuket City Phokeethra Hotel', 'Phuket Town', 'Phuket'),
('Royal Phuket City Hotel', 'Phuket Town', 'Phuket'),
('The Memory at On On Hotel', 'Phuket Town', 'Phuket'),
('The Neighbors Hostel - Adults Only', 'Phuket Town', 'Phuket'),
('Hotel Midtown Ratsada', 'Phuket Town', 'Phuket'),
('Ratri Hotel Phuket Old Town', 'Phuket Town', 'Phuket'),
('ibis Styles Phuket City Hotel', 'Phuket Town', 'Phuket'),
('Nora Bukit Hotel', 'Phuket Town', 'Phuket'),
('EcoLoft Hotel', 'Phuket Town', 'Phuket'),
('Bedline Hotel', 'Phuket Town', 'Phuket'),
('Isara Boutique Hotel and Cafe', 'Phuket Town', 'Phuket'),
('The Tint at Phuket town', 'Phuket Town', 'Phuket'),
('Quip Bed & Breakfast Phuket Hotel', 'Phuket Town', 'Phuket'),
('The Dorm Hostel', 'Phuket Town', 'Phuket'),
('Grand Supicha City Hotel', 'Phuket Town', 'Phuket'),
('Crystal Inn Phuket', 'Phuket Town', 'Phuket'),
('Sino House Phuket Hotel', 'Phuket Town', 'Phuket'),
('Samkong Place', 'Phuket', 'Phuket'),
('Pure Phuket Residence', 'Phuket Town', 'Phuket'),
('Aekkeko Hostel', 'Phuket Town', 'Phuket'),
('Blu Monkey Hub and Hotel Phuket', 'Phuket Town', 'Phuket'),
('The Blanket Hotel', 'Phuket', 'Phuket'),
('Recenta Style Phuket Town', 'Phuket Town', 'Phuket'),
('Phuket Chinoinn Hotel', 'Phuket Town', 'Phuket'),
('Mei Zhou Phuket Hotel', 'Phuket Town', 'Phuket'),
('Lamoon Resotel', 'Phuket Town', 'Phuket'),
('The Malika', 'Phuket Town', 'Phuket'),
('Casa Blanca Boutique hotel', 'Phuket Town', 'Phuket'),
('Phuket 346 Guest House', 'Phuket Town', 'Phuket'),
('Pattra Mansion by AKSARA Collection', 'Phuket Town', 'Phuket'),
('Xinlor House', 'Phuket Town', 'Phuket'),
('Rabbitel Phuket', 'Phuket Town', 'Phuket'),
('99 OLDTOWN BOUTIQUE GUESTHOUSE', 'Phuket Town', 'Phuket'),
('The Besavana Phuket', 'Phuket Town', 'Phuket'),
('Sugar Palm Residence', 'Phuket Town', 'Phuket'),
('Phuket Merlin Hotel', 'Phuket Town', 'Phuket'),
('Book a Bed Poshtel - Hostel', 'Phuket Town', 'Phuket'),
('Chinotel', 'Phuket Town', 'Phuket'),
('Fulfill Phuket Hostel', 'Phuket Town', 'Phuket'),
('I Pavilion Hotel Phuket', 'Phuket Town', 'Phuket'),
('Cool Residence', 'Phuket Town', 'Phuket'),
('Bhukitta Boutique Hotel', 'Phuket Town', 'Phuket'),
('Pek House', 'Phuket Town', 'Phuket'),
('Meroom', 'Phuket Town', 'Phuket'),
('In Phuket House', 'Phuket Town', 'Phuket'),
('The Little Nest Phuket', 'Phuket Town', 'Phuket'),
('Phuket Old Town Hostel', 'Phuket Town', 'Phuket'),
('Blu Monkey Boutique Phuket Town', 'Phuket Town', 'Phuket'),
('Sleep at Phuket', 'Phuket', 'Phuket'),
('Chino Town at Yaowarat Phuket', 'Phuket', 'Phuket'),
('Lub Sbuy Hostel', 'Phuket Town', 'Phuket'),
('The Arbern Hostel x Bistro', 'Phuket Town', 'Phuket'),
('Baan PhuAnda Phuket', 'Phuket Town', 'Phuket'),
('Tee Pak Dee Resident Phuket', 'Phuket Town', 'Phuket'),
('Lub Sbuy House', 'Phuket Town', 'Phuket'),
('Blu Monkey Bed & Breakfast Phuket', 'Phuket Town', 'Phuket'),
('The Topaz Residence', 'Phuket Town', 'Phuket'),
('Chino Town Gallery Alley', 'Phuket Town', 'Phuket'),
('Snoozy', 'Phuket Town', 'Phuket'),
('D''s Corner & Guesthouse', 'Phuket Town', 'Phuket'),
('HAO Hotel Phuket', 'Phuket Town', 'Phuket'),
('Woo Gallery and Boutique Hotel', 'Phuket Town', 'Phuket'),
('Machima House', 'Phuket Town', 'Phuket'),
('Peranakan Boutique Hotel', 'Phuket', 'Phuket'),
('Phupara Place', 'Phuket Town', 'Phuket'),
('The Pho Thong Phuket', 'Phuket Town', 'Phuket'),
('Sleep Sheep Phuket Hostel SHA', 'Phuket Town', 'Phuket'),
('S.B. Living Place', 'Phuket Town', 'Phuket'),
('Na Siam Guesthouse', 'Phuket Town', 'Phuket'),
('The Rommanee Classic Guesthouse', 'Phuket Town', 'Phuket'),
('Surachet at 257 Boutique House', 'Phuket Town', 'Phuket'),
('Ming Shou Boutique House', 'Phuket Town', 'Phuket'),
('Borbaboom Poshtel - Hostel', 'Phuket Town', 'Phuket'),
('217 at HKT', 'Phuket Town', 'Phuket'),
('Hostel Our Nomad', 'Phuket Town', 'Phuket'),
('The Z Nite Hostel', 'Phuket Town', 'Phuket'),
('Sound Gallery House - Hostel', 'Phuket Town', 'Phuket'),
('Ananas Phuket Hostel', 'Surin', 'Phuket');

-- =====================================================
-- PHANG NGA HOTELS (235 hotels)
-- =====================================================

INSERT INTO reference_hotels (name, area, province) VALUES
('Bedter Hotel Phang Nga', 'Mueang Phang Nga', 'Phang Nga'),
('White House', 'Mueang Phang Nga', 'Phang Nga'),
('Katathong Golf Resort & Spa', 'Phang Nga', 'Phang Nga'),
('Bor Saen Pool Villa', 'Phang Nga', 'Phang Nga'),
('Lukmuang 2 Hotel', 'Phang Nga', 'Phang Nga'),
('Le Erawan Hotel', 'Phang Nga', 'Phang Nga'),
('Phu Nga Hotel', 'Phang Nga', 'Phang Nga'),
('Manora Garden B & B', 'Phang Nga', 'Phang Nga'),
('The Sleep Phang Nga', 'Phang Nga Town', 'Phang Nga'),
('Baan Rim Nam Resort', 'Phang Nga', 'Phang Nga'),
('Phang Nga Guesthouse', 'Phang Nga Town', 'Phang Nga'),
('Ingthara Resort', 'Phang Nga', 'Phang Nga'),
('Home Phang-Nga Guesthouse', 'Phang Nga', 'Phang Nga'),
('Pranee Home', 'Phang Nga', 'Phang Nga'),
('Najjamee Bungalows Koh Yao Noi', 'Koh Yao Noi', 'Phang Nga'),
('Thaweesuk Hotel', 'Phang Nga', 'Phang Nga'),
('Blue Mountain Phangnga Resort', 'Phang Nga', 'Phang Nga'),
('Guesthouse 88', 'Phang Nga', 'Phang Nga'),
('Tayida Resort & Homestay', 'Phang Nga', 'Phang Nga'),
('B.O Best Residence', 'Phang Nga', 'Phang Nga'),
('Tambai Resort', 'Phang Nga', 'Phang Nga'),
('JW Marriott Khao Lak Resort and Spa', 'Khao Lak', 'Phang Nga'),
('The Sands Khao Lak by Katathani', 'Khao Lak', 'Phang Nga'),
('The Little Shore Khao Lak by Katathani', 'Khao Lak', 'Phang Nga'),
('Le Meridien Khao Lak Resort & Spa', 'Khao Lak', 'Phang Nga'),
('Grand Mercure Khao Lak Bangsak', 'Khao Lak', 'Phang Nga'),
('Robinson Khao Lak', 'Khao Lak', 'Phang Nga'),
('Ayara Villas Khaolak', 'Khao Lak', 'Phang Nga'),
('Moracea by Khao Lak Resort', 'Khao Lak', 'Phang Nga'),
('The Leaf On The Sands by Katathani', 'Phang Nga', 'Phang Nga'),
('La Flora Khao Lak', 'Khao Lak', 'Phang Nga'),
('Aleenta Phuket - Phang Nga', 'Phang Nga Town', 'Phang Nga'),
('X10 Khaolak', 'Khao Lak', 'Phang Nga'),
('Khaolak Merlin Resort', 'Khao Lak', 'Phang Nga'),
('Khao Lak Marriott Beach Resort & Spa', 'Khao Lak', 'Phang Nga'),
('Six Senses Yao Noi', 'Koh Yao', 'Phang Nga'),
('Outrigger Khao Lak Beach Resort', 'Khao Lak', 'Phang Nga'),
('Cape Kudu Hotel', 'Koh Yao Noi', 'Phang Nga'),
('La Vela Khao Lak', 'Khao Lak', 'Phang Nga'),
('The Haven Khao Lak', 'Khao Lak', 'Phang Nga'),
('Natai Beach Resort', 'Natai', 'Phang Nga'),
('Sentido Khaolak', 'Khao Lak', 'Phang Nga'),
('Graceland Khaolak Beach Resort', 'Khao Lak', 'Phang Nga'),
('The Leaf Oceanside', 'Khuk Khak', 'Phang Nga'),
('TreeHouse Villas - Adults Only', 'Koh Yao', 'Phang Nga'),
('Santhiya Phuket Natai Resort & Spa', 'Natai', 'Phang Nga'),
('Devasom Khao Lak Beach Resort & Villas', 'Khao Lak', 'Phang Nga'),
('Bangsak Village - Adults Only', 'Bang Sak', 'Phang Nga'),
('Thiw Son Beach Resort', 'Koh Yao', 'Phang Nga'),
('The Waters Khao Lak by Katathani', 'Khao Lak', 'Phang Nga'),
('The Chu’s boutique hotel', 'Phang Nga', 'Phang Nga'),
('JW Marriott Khao Lak Resort Suites', 'Khao Lak', 'Phang Nga'),
('Beyond Skywalk Nangshi', 'Phang Nga', 'Phang Nga'),
('Kalima Resort & Villas Khaolak', 'Khao Lak', 'Phang Nga'),
('Paradise KohYao', 'Koh Yao', 'Phang Nga'),
('Ramada Resort by Wyndham Khao Lak', 'Khao Lak', 'Phang Nga'),
('Khao Lak Palm Beach Resort', 'Khao Lak', 'Phang Nga'),
('Eden Beach Khaolak Resort and Spa A Lopesan Collection Hotel', 'Khao Lak', 'Phang Nga'),
('Le Menara Khao Lak', 'Khao Lak', 'Phang Nga'),
('Koh Yao Yai Hillside Resort', 'Koh Yao Yai', 'Phang Nga'),
('The Sarojin', 'Phang Nga', 'Phang Nga'),
('Chongfah Resort', 'Takua Pa', 'Phang Nga'),
('Purana Resort Koh Yao Noi', 'Koh Yao Noi', 'Phang Nga'),
('APSARA Beachfront Resort and Villa', 'Phang Nga', 'Phang Nga'),
('Kokotel Khao Lak Lighthouse', 'Khao Lak', 'Phang Nga'),
('Bangmara Hill', 'Phang Nga', 'Phang Nga'),
('The Briza Beach Resort Khaolak', 'Khao Lak', 'Phang Nga'),
('Khaolak Oriental Resort', 'Khao Lak', 'Phang Nga'),
('Baan Khaolak Beach Resort', 'Khao Lak', 'Phang Nga'),
('Hotel Gahn', 'Phang Nga', 'Phang Nga'),
('Casa de La Flora', 'Khuk Khak', 'Phang Nga'),
('Palm Galleria Resort', 'Phang Nga', 'Phang Nga'),
('Good Morning Hotel at TakuaPa', 'Takua Pa', 'Phang Nga'),
('Koyao Island Resort', 'Koh Yao', 'Phang Nga'),
('Isara Khao Lak', 'Khao Lak', 'Phang Nga'),
('The Mouth Resort', 'Khuk Khak', 'Phang Nga'),
('Sudala Beach Resort', 'Khuk Khak', 'Phang Nga'),
('Nautical Home & Seashell House B&B', 'Phang Nga', 'Phang Nga'),
('Khaolak Bhandari Resort & Spa', 'Khao Lak', 'Phang Nga'),
('Fanari Khaolak Resort - Courtyard Zone', 'Khao Lak', 'Phang Nga'),
('Baan Kong Hostel', 'Phang Nga', 'Phang Nga'),
('Takuapa Station Hotel', 'Takua Pa', 'Phang Nga'),
('Mai Khao Lak Beach Resort & Spa (TUI BLUE Mai Khaolak)', 'Khao Lak', 'Phang Nga'),
('Seaview Resort Khao Lak', 'Khao Lak', 'Phang Nga'),
('Dan''s Koyao Retreat', 'Koh Yao Noi', 'Phang Nga'),
('Cousin Resort', 'Phang Nga', 'Phang Nga'),
('Beyond Khaolak', 'Khao Lak', 'Phang Nga'),
('Baan Krating Khao Lak Resort', 'Khao Lak', 'Phang Nga'),
('Nankanok Bungalow', 'Koh Yao', 'Phang Nga'),
('Kuapa Resort', 'Phang Nga', 'Phang Nga'),
('Khaolak Laguna Resort', 'Khao Lak', 'Phang Nga'),
('ThaiLife Wellness and Meditation Resort', 'Phang Nga', 'Phang Nga'),
('Bai Bai Home', 'Phang Nga', 'Phang Nga'),
('Khaolak Wanaburee Resort', 'Khao Lak', 'Phang Nga'),
('Khaolak Emerald Beach Resort and Spa', 'Khao Lak', 'Phang Nga'),
('Kokotel Khao Lak Isara Casa', 'Khao Lak', 'Phang Nga'),
('Les Fleurs', 'Phang Nga', 'Phang Nga'),
('9 Hornbills Tented Camp', 'Koh Yao', 'Phang Nga'),
('The Hotspring Beach Resort & Spa', 'Phang Nga', 'Phang Nga'),
('Samet Nangshe Goodview', 'Phang Nga', 'Phang Nga'),
('Sunset Khaolak Resort', 'Khao Lak', 'Phang Nga'),
('Khaolak Boutique Heritage', 'Khao Lak', 'Phang Nga'),
('Merlin Plaza Apartments', 'Phang Nga', 'Phang Nga'),
('Elephant Hills Khao Sok', 'Phang Nga', 'Phang Nga'),
('Khaolak Bay Front Resort', 'Khao Lak', 'Phang Nga'),
('Khaolak Summer House Resort', 'Khao Lak', 'Phang Nga'),
('Khaolak Summer House Resort 2', 'Khao Lak', 'Phang Nga'),
('Haadson Resort', 'Phang Nga', 'Phang Nga'),
('Ruk Cozy Khao Lak', 'Khao Lak', 'Phang Nga'),
('Baba Beach Club Natai Luxury Pool Villa Hotel by Sri panwa', 'Natai', 'Phang Nga'),
('Khaolak Suthawan Resort', 'Khao Lak', 'Phang Nga'),
('The Anda Mani Khaolak Beachfront Villas', 'Khao Lak', 'Phang Nga'),
('Three ladies', 'Koh Yao', 'Phang Nga'),
('Khaolak Palm Hill Resort', 'Khao Lak', 'Phang Nga'),
('Fondness Hotel', 'Phang Nga', 'Phang Nga'),
('Jaiyen Eco Resort', 'Koh Yao', 'Phang Nga'),
('Baanchongfa Resort', 'Phang Nga', 'Phang Nga'),
('R.T. Hotel', 'Khao Lak', 'Phang Nga'),
('Sunrise Beach Koh Yao Resort', 'Koh Yao', 'Phang Nga'),
('Le Passe-Temps', 'Phang Nga', 'Phang Nga'),
('Khao Lak Relax Resort', 'Khao Lak', 'Phang Nga'),
('White Cat Hotel', 'Phang Nga', 'Phang Nga'),
('Theppahrak Home', 'Takua Pa', 'Phang Nga'),
('Koyao Bay Pavilions', 'Koh Yao', 'Phang Nga'),
('The Glory Gold Hotel', 'Khao Lak', 'Phang Nga'),
('Laguna Villas Boutique Hotel', 'Koh Yao Noi', 'Phang Nga'),
('Mai Holiday By Mai Khao Lak', 'Khao Lak', 'Phang Nga'),
('Khaolak Forest Resort', 'Khao Lak', 'Phang Nga'),
('The Leaf on the Sands by Katathani', 'Phang Nga', 'Phang Nga'),
('Srichada Hotel Khaolak', 'Khao Lak', 'Phang Nga'),
('Andamania Beach Resort', 'Takua Pa', 'Phang Nga'),
('Sawasdee Lagoon Resort', 'Phang Nga', 'Phang Nga'),
('Khaolak Orchid Beach Resort', 'Khao Lak', 'Phang Nga'),
('Big Sun Residence by iRETREAT', 'Koh Yao', 'Phang Nga'),
('The Simple Koh Yao Noi', 'Koh Yao Noi', 'Phang Nga'),
('Le Coral Beach Resort and Cafe', 'Natai', 'Phang Nga'),
('Anattaya Holiday Home', 'Koh Yao Noi', 'Phang Nga'),
('Kantary Beach Hotel Villas & Suites, Khao Lak', 'Khao Lak', 'Phang Nga'),
('Khao Lak Blue Lagoon Resort', 'Khao Lak', 'Phang Nga'),
('Iniala Beach House', 'Phang Nga', 'Phang Nga'),
('Kokotel Khao Lak Seascape', 'Khao Lak', 'Phang Nga'),
('The Grand Southsea Khaolak Beach Resort', 'Khao Lak', 'Phang Nga'),
('Ocean Breeze Resort Khao Lak', 'Khao Lak', 'Phang Nga'),
('Kokotel Khao Lak Montana', 'Khao Lak', 'Phang Nga'),
('Loma Resort', 'Phang Nga', 'Phang Nga'),
('Sabai Corner Bungalows', 'Koh Yao', 'Phang Nga'),
('Khaolak Paradise Resort', 'Khao Lak', 'Phang Nga'),
('Motive Cottage Resort', 'Phang Nga', 'Phang Nga'),
('Fanari Khaolak Resort - Seafront Wing', 'Khao Lak', 'Phang Nga'),
('Bangsak Merlin Resort', 'Bang Sak', 'Phang Nga'),
('Seabox Khaolak Hostel', 'Khao Lak', 'Phang Nga'),
('OYO 619 Water Palm Resort', 'Phang Nga', 'Phang Nga'),
('Andamania Beach Resort & Spa', 'Takua Pa', 'Phang Nga'),
('Natai House', 'Natai', 'Phang Nga'),
('Palm Garden Resort Khaolak', 'Khao Lak', 'Phang Nga'),
('Khaolak Sunset Resort - Adults Only (SHA Extra Plus)', 'Khao Lak', 'Phang Nga'),
('Zimbei Cozytel Khaolak', 'Khao Lak', 'Phang Nga'),
('Takolaburi Cultural Resort', 'Phang Nga', 'Phang Nga'),
('Erawan Hotel', 'Phang Nga', 'Phang Nga'),
('Lantala Residence', 'Phang Nga', 'Phang Nga'),
('Bann Anattaya Koh Yao Noi', 'Koh Yao Noi', 'Phang Nga'),
('Sweet Mango Khaolak', 'Khao Lak', 'Phang Nga'),
('MJ Boutique Hotel Khao Lak', 'Khao Lak', 'Phang Nga'),
('Ao Thong Beach Bungalows & Restaurant', 'Khao Lak', 'Phang Nga'),
('DKaYa Hostel', 'Phang Nga', 'Phang Nga'),
('Chomphu Resort Khaolak', 'Khao Lak', 'Phang Nga'),
('Khaolak Mohintara Resort', 'Khao Lak', 'Phang Nga'),
('Villa Colina', 'Phang Nga', 'Phang Nga'),
('2025-07-12 02:10:00', 'Phang Nga', 'Phang Nga'),
('Khaolak Hillside Villa', 'Khao Lak', 'Phang Nga'),
('Khaolak Mountain View', 'Khao Lak', 'Phang Nga'),
('Casacool Hotel Khoalak', 'Phang Nga', 'Phang Nga'),
('Tuaprodhome', 'Phang Nga', 'Phang Nga'),
('Baan Mek Lom', 'Phang Nga', 'Phang Nga'),
('Garden Villa Khaolak', 'Khao Lak', 'Phang Nga'),
('Gerd and Noi Resort Khao Lak', 'Khao Lak', 'Phang Nga'),
('Nestvilla Khok-kloi Phang-nga', 'Phang Nga', 'Phang Nga'),
('Holiday Resort Ko Yao', 'Koh Yao', 'Phang Nga'),
('Khaolak Paradise Resort', 'Khao Lak', 'Phang Nga'),
('Bangsak Hut', 'Takua Pa', 'Phang Nga'),
('Capital O 75518 Baan Rose Resort Ao Luk', 'Phang Nga', 'Phang Nga'),
('Leam Sai Bungalows Koh Yao Noi', 'Koh Yao Noi', 'Phang Nga'),
('AP Hotel', 'Phang Nga', 'Phang Nga'),
('Khao Lak Riverside Resort & Spa', 'Khao Lak', 'Phang Nga'),
('Mukdara Beach Villa & Spa Resort', 'Khuk Khak', 'Phang Nga'),
('To Zleep Hotel Khaolak', 'Khao Lak', 'Phang Nga'),
('Phurafa Resort', 'Phang Nga', 'Phang Nga'),
('OYO 75517 Mananchaya Resort', 'Phang Nga', 'Phang Nga'),
('Slumber Party Surf Khao Lak Hostel', 'Khao Lak', 'Phang Nga'),
('Kunna House', 'Koh Yao', 'Phang Nga'),
('The Retreat Khaolak Resort', 'Khao Lak', 'Phang Nga'),
('Bania Boutique House', 'Phang Nga', 'Phang Nga'),
('Khaolak C-nior Bungalows', 'Khao Lak', 'Phang Nga'),
('Suksompong Resort', 'Takua Pa', 'Phang Nga'),
('Awana Villa Resort Yaonoi', 'Koh Yao Noi', 'Phang Nga'),
('Khao Lak Golden Coconut Resort', 'Khao Lak', 'Phang Nga'),
('At Bangsak Resort', 'Bang Sak', 'Phang Nga'),
('Khaolak Grand City', 'Khao Lak', 'Phang Nga'),
('Hongte Khaolak Resort', 'Khao Lak', 'Phang Nga'),
('OYO 75304 Riverside Guesthouse', 'Khao Lak', 'Phang Nga'),
('APA-TREE Boutique Hotel', 'Phang Nga', 'Phang Nga'),
('The Oasis Khaolak Resort', 'Khao Lak', 'Phang Nga'),
('Lah Own Khaolak Resort', 'Khao Lak', 'Phang Nga'),
('Baan Chong Fa Resort', 'Phang Nga', 'Phang Nga'),
('Banana Lodge', 'Phang Nga', 'Phang Nga'),
('Buppha Resort', 'Phang Nga', 'Phang Nga'),
('Grandfather Khao Lak Resort', 'Khao Lak', 'Phang Nga'),
('Baan Khao Lak Resort', 'Khao Lak', 'Phang Nga'),
('Tha Khao Bay View', 'Koh Yao', 'Phang Nga'),
('Mae-Porn Hostel', 'Khao Lak', 'Phang Nga'),
('Mookdamun Bungalows', 'Koh Yao Noi', 'Phang Nga'),
('Koh Yao Chukit Dachanan Resort', 'Koh Yao', 'Phang Nga'),
('Khaolak Mind Home Hostel - Adults Only', 'Khao Lak', 'Phang Nga'),
('Betterview Bed Breakfast & Bungalow', 'Koh Yao', 'Phang Nga'),
('Ranyatavi Resort', 'Phang Nga', 'Phang Nga'),
('Ladda Resort', 'Khao Lak', 'Phang Nga'),
('Baan Bamboo Resort', 'Phang Nga', 'Phang Nga'),
('Reuanpruhong Na Bangthong', 'Phang Nga', 'Phang Nga'),
('Jerung Hotel', 'Phang Nga', 'Phang Nga'),
('Leelawadee Resort Khaolak', 'Khao Lak', 'Phang Nga'),
('OYO 75331 Hareeya Hotel', 'Phang Nga', 'Phang Nga'),
('Pasai Beach Lodge', 'Koh Yao', 'Phang Nga'),
('Namkhem Inn', 'Phang Nga', 'Phang Nga'),
('Namkhem Inn 2', 'Phang Nga', 'Phang Nga'),
('Sun Globe Resort', 'Koh Yao Noi', 'Phang Nga'),
('Niramaya Villa and Wellness', 'Koh Yao', 'Phang Nga'),
('Makai NAP', 'Phang Nga', 'Phang Nga'),
('OYO 732 Juthamas Hotel', 'Phang Nga', 'Phang Nga'),
('At Home Khaolak', 'Khao Lak', 'Phang Nga'),
('Coconut Homes & Cafe', 'Phang Nga', 'Phang Nga'),
('Rnana Grand', 'Phang Nga', 'Phang Nga'),
('Wandee Bed and Breakfast - Hostel', 'Phang Nga', 'Phang Nga'),
('We Hostel', 'Phang Nga', 'Phang Nga'),
('Villa Chaya', 'Phang Nga', 'Phang Nga'),
('Nimit Bungalow', 'Phang Nga', 'Phang Nga');

-- Create indexes for better performance (indexes already exist from 008 migration)
-- CREATE INDEX IF NOT EXISTS idx_reference_hotels_name ON reference_hotels(name);
-- CREATE INDEX IF NOT EXISTS idx_reference_hotels_area ON reference_hotels(area);
-- CREATE INDEX IF NOT EXISTS idx_reference_hotels_province ON reference_hotels(province);

-- Summary
-- Total hotels imported: 1998
